# -*- coding: utf-8 -*-
# Ecliptica 数据 Part 7b: 流派 Build（真实网上攻略）
# 法锤/盾法师/奇术师/猫灵师：图鉴站构筑 + 日文wiki build 双来源

BUILDS_B = [
 # ============ Spellhammer（法锤） ============
 {"classId":"spellhammer","archetypeId":"codex","archetype":"跃击流（图鉴站）","patch":"v0.51","title":"跃击（Jump Smash）高机动输出流","source":"Ecliptica Codex 中文图鉴站构筑（36点规划）",
  "note":"常规：输出=迅捷之手、力量、熟练（跃击）、极意（跃击）、巨力（跃击）、震荡（跃击）；生存=不屈韧性、最后一搏、又大又圆、导电护甲、铁皮；节奏=弹簧足、练腿日。可选：输出=熟练（跃击）、力量、全力专注；生存=蓬蓬、贪食者、质量之相；节奏=弹簧足、快速呼吸。",
  "must":[
   {"id":"strength","count":7,"reason":"物理伤害 +10%/层"},
   {"id":"swift_hands","count":6,"reason":"攻速 +15%/层。法锤普攻（Pummel）挥锤期间移速×2（随移速缩放）——攻速=挥锤/突进频率，空中快速机动与连段全靠它（wiki 机制）"},
   {"id":"springfoot","count":5,"reason":"跳跃高度 +20%/层（跃击伤害随高度缩放）"},
   {"id":"sh_prof_jump","count":5,"reason":"击退力度+跃击强度（熟练·跃击）"},
   {"id":"athletic","count":2,"reason":"移速 +8%"},
   {"id":"leg_day","count":2,"reason":"移速+跳高（练腿日）"},
   {"id":"sh_mastery_jump","count":2,"reason":"踩头顶跃击冷却 -25%（极意·跃击）"},
   {"id":"conductive_armor","count":1,"reason":"物理防御+出血抗性"},
   {"id":"iron_skin","count":1,"reason":"防御 +8%"},
   {"id":"big_and_round","count":1,"reason":"击退抗性+最大生命"},
   {"id":"last_stand","count":1,"reason":"保命"},
   {"id":"volatile_tenacity","count":1,"reason":"保命"},
   {"id":"sh_juggernaut_jump","count":1,"reason":"高功率跃击获得强化防御（巨力）"},
   {"id":"sh_concussion_jump","count":1,"reason":"高功率跃击附加雷电+50%麻痹（震荡）"},
  ],
  "nice":[
   {"id":"sh_prof_chuck","reason":"可选：熟练（投掷）"},
   {"id":"full_focus","reason":"可选：全力专注"},
   {"id":"fluffy","reason":"可选生存：蓬蓬"},
   {"id":"gluttonous","reason":"可选生存：贪食者"},
   {"id":"mass_aspect","reason":"可选生存：质量之相"},
   {"id":"springfoot","reason":"可选节奏：弹簧足（可继续加）"},
   {"id":"quick_breath","reason":"可选节奏：快速呼吸"},
  ],
  "avoid":[],
  "playstyle":"跃击流：弹簧足+熟练（跃击）堆高度与强度，极意踩头减CD连段，巨力/震荡提供生存与控制。构筑由中文图鉴站生成，未验证，按实际情况灵活调整。注：抛锤（Chuck）核爆流暂缺权威加点参考。",
  "reroll":""},
 {"classId":"spellhammer","archetypeId":"bilichuck","archetype":"抛锤核爆流（B站）","patch":"v0.51 (2026-07-29)","title":"蓄力投掷核爆流","source":"B站视频《一锤一锤核爆锤》（落羽松_Taxod 08-02 实机）+ 评论区 JO丁 实测评价",
  "note":"实机经验（视频口述 ASR）：玩锤主要都要点移速；丢锤不太需要跳高但需要弹速（丢进去的物体速度）；'丢垂一般叠一个三四个就够用，主玩丢垂几乎不（普攻）要叠四五六个'；跳锤对移速和跳高都需要。评论区：'跳锤扔锤各有各的好，扔锤在尾王也能打输出，跳锤伤害高但尾王会被肘飞，只能打罐子；扔锤可以自己处理空中单位'。核爆玩法：白嫖符文互叠起爆符，白拿至少 6 个力量（视频简介）；本局下砸伤害上限约 1550。",
  "must":[
   {"id":"sh_prof_chuck","count":3,"reason":"投掷熟练 3-4 个就够用（视频实测：'丢垂一般叠一个三四个就够用'）"},
   {"id":"eagle_eye","count":2,"reason":"丢锤需要弹速（丢进去的物体速度），不太需要跳高（视频实测）"},
   {"id":"athletic","count":3,"reason":"玩锤主要肯定要点移速（视频实测：'玩垂主要不然拿两个方法他都是要玩那个家移速的'）"},
   {"id":"sh_juggernaut_chuck","count":1,"reason":"满蓄力投掷→强力 buff；核爆核心（上限 5 层+2/升级）"},
   {"id":"sh_mastery_chuck","count":1,"reason":"弹跳+1 次；核爆玩法组件"},
   {"id":"heavy_hand","count":1,"reason":"单发高伤适配（投掷不吃攻速流）；评论区推荐拿重手"},
   {"id":"glass_cannon","count":1,"reason":"不怂可以拿玻璃大炮（JO丁 枪手同思路，单发流通用）"},
  ],
  "nice":[
   {"id":"strength","count":None,"reason":"物理伤害核心"},
   {"id":"sh_concussion_chuck","count":1,"reason":"投掷命中 AOE 电伤+麻痹"},
   {"id":"smell_the_roses","count":1,"reason":"低血量保命"},
   {"id":"partial_flight","count":1,"reason":"二段跳走位"},
   {"id":"volatile_tenacity","count":1,"reason":"保命"},
  ],
  "avoid":[
   {"id":"rapid_fire","reason":"攻速流与投掷蓄力流冲突"},
   {"id":"swift_hands","reason":"蓄力投掷不吃攻速"},
   {"id":"way_of_the_law","reason":"节奏随机"},
  ],
  "playstyle":"蓄力投掷为主（满蓄力准星变红出手）：尾王也能打输出、可自理空中单位；核爆锤玩法：起爆符符文互叠白嫖力量。跳锤（跃击流）伤害更高但尾王会被肘飞，仅清罐子用（JO丁 实测对比）。",
  "reroll":"红找重手/玻璃炮/投掷系；蓝绿补物理伤害与移速弹速。"},

 # ============ Shield Mage（盾法师） ============
 {"classId":"shieldmage","archetypeId":"codex","archetype":"守望机动坦（图鉴站）","patch":"v0.51","title":"战术冷却+团队支援坦","source":"Ecliptica Codex 中文图鉴站构筑（36点规划）",
  "note":"常规：生存=导电护甲、铁皮、不破、又大又圆、不屈韧性、最后一搏；团队=守望、集结、熟练、极意；节奏=快速呼吸、运动健将。可选：生存=贪食者、蓬蓬、质量之相；节奏=又大又快、练腿日。",
  "must":[
   {"id":"quick_breath","count":10,"reason":"战术冷却 +10%/层（护盾/机动频率核心）"},
   {"id":"sm_unbreakable","count":8,"reason":"紫攻击伤害 -5%/层+护盾额外减免（不破）"},
   {"id":"athletic","count":4,"reason":"移速 +8%/层"},
   {"id":"conductive_armor","count":3,"reason":"物理防御+出血抗性"},
   {"id":"sm_proficiency","count":3,"reason":"防御姿态盾范围扩大（熟练）"},
   {"id":"iron_skin","count":2,"reason":"防御 +8%"},
   {"id":"big_and_round","count":2,"reason":"击退抗性+最大生命"},
   {"id":"last_stand","count":1,"reason":"保命"},
   {"id":"volatile_tenacity","count":1,"reason":"保命"},
   {"id":"sm_rally_up","count":1,"reason":"护盾给全队赋能（集结）"},
   {"id":"sm_warden","count":1,"reason":"护盾给全队韧性可挡一次（守望，代价战术CD+50%）"},
  ],
  "nice":[
   {"id":"gluttonous","reason":"可选生存：贪食者"},
   {"id":"fluffy","reason":"可选生存：蓬蓬"},
   {"id":"mass_aspect","reason":"可选生存：质量之相"},
   {"id":"big_and_speedy","reason":"可选节奏：又大又快"},
   {"id":"leg_day","reason":"可选节奏：练腿日"},
  ],
  "avoid":[],
  "playstyle":"战术冷却流：快速呼吸×10 让护盾/机动几乎常驻；守望+集结提供团队支援。注意守望战术CD+50%的代价已被快速呼吸部分抵消。构筑由中文图鉴站生成，未验证，按实际情况灵活调整。",
  "reroll":""},
 {"classId":"shieldmage","archetypeId":"jpwiki","archetype":"站桩坦流（日文wiki）","patch":"v0.50 (2026-07-08)","title":"站桩坦克（相信队友）","source":"日文wiki build页（シールドメイジビルド）",
  "note":"以通关为前提的 build 方案。必须：大且懒1-3、生命力10、不破8-10、熟练2-3、最后抵抗1、不稳定韧性1、巨大且迅捷1；准必须：HP 150-250（多了用玻璃炮回调）、净化祝福1、雷霆光环1-2、导电护甲1-2、冰爆1；非推荐：守望者（CD+50%太重）。",
  "must":[
   {"id":"big_and_lazy","count":3,"reason":"站桩自然回复翻倍（1-3 层），坦度核心"},
   {"id":"vitality","count":10,"reason":"自然回复是坦主要恢复源（按大且懒取得度调整）"},
   {"id":"sm_unbreakable","count":9,"reason":"紫攻击减免+钉住敌人（8-10 层）"},
   {"id":"sm_proficiency","count":3,"reason":"盾范围扩大（2-3 层）"},
   {"id":"last_stand","count":1,"reason":"事故保险"},
   {"id":"volatile_tenacity","count":1,"reason":"同上"},
   {"id":"big_and_speedy","count":1,"reason":"辅助CD加快=仇恨节奏（防御-20%注意）"},
  ],
  "nice":[
   {"id":"fluffy","count":None,"reason":"HP 补到 150-250；太高可用玻璃炮回调"},
   {"id":"big_and_round","count":None,"reason":"HP+击退抗性（别堆满击退抗性）"},
   {"id":"benison_purification","count":1,"reason":"免费输出+虚弱减伤"},
   {"id":"thunder_aura","count":2,"reason":"免费AOE+麻痹"},
   {"id":"conductive_armor","count":2,"reason":"物理抗性+出血抗性"},
   {"id":"sm_ice_burst","count":1,"reason":"格挡转输出"},
  ],
  "avoid":[
   {"id":"sm_warden","reason":"辅助CD +50% 代价太重（v0.51 缓和后仍重）"},
  ],
  "playstyle":"杂鱼战保护后排仇恨；门卫战拉仇恨到角落站桩成为掩体；紫攻击必须开护罩/躲。站得住就赢。",
  "reroll":"大且懒+不坏是硬目标；Eclipse 难度前还没拿到大且懒→考虑转生重开。"},

 # ============ Thaumaturge（奇术师/书奶） ============
 {"classId":"thaumaturge","archetypeId":"codex","archetype":"综合构筑（图鉴站）","patch":"v0.51","title":"攻速移速综合奶","source":"Ecliptica Codex 中文图鉴站构筑（36点规划）",
  "note":"常规：输出=熟练、极意、锐眼、潜能激发、永命、迅捷之手；生存=不屈韧性、最后一搏、铁皮、导电护甲、又大又圆、蓬蓬、应激恐慌；节奏=运动健将。可选：输出=充能打击、集中、烈焰之魂、冰封之心、毒素之相、智力过高；生存=质量之相、健康守卫；节奏=轻羽、快速呼吸。可选路线：烈焰/冰封——抽到烈焰之魂/冰封之心后放弃全力专注，继续升级迅捷之手；充能打击——抽到充能打击后放弃迅捷之手，走纯暴击伤害路线升级全力专注。",
  "must":[
   {"id":"swift_hands","count":7,"reason":"攻速 +15%/层（治疗节奏核心）"},
   {"id":"athletic","count":7,"reason":"移速 +8%/层"},
   {"id":"th_mastery","count":5,"reason":"痛楚交换能量消耗 -3%/层（加算，8层降至1%）"},
   {"id":"conductive_armor","count":2,"reason":"物理防御+出血抗性"},
   {"id":"big_and_round","count":2,"reason":"击退抗性+最大生命"},
   {"id":"th_keen_eye","count":2,"reason":"痛楚交换射程 +15米/层"},
   {"id":"th_proficiency","count":2,"reason":"治疗量+3、冷却-10%/层"},
   {"id":"fluffy","count":1,"reason":"最大生命 +10（蓬蓬）"},
   {"id":"iron_skin","count":1,"reason":"防御 +8%"},
   {"id":"last_stand","count":1,"reason":"保命"},
   {"id":"volatile_tenacity","count":1,"reason":"保命"},
   {"id":"hawkeye","count":1,"reason":"弹道距离+散布（猎鹰之眼）"},
   {"id":"eagle_eye","count":1,"reason":"弹速 +35%（鹰眼）"},
   {"id":"reactive_panic","count":1,"reason":"受伤叠狂怒"},
   {"id":"th_doping","count":1,"reason":"痛楚交换目标获得强化防御（潜能激发，自身最多3层）"},
   {"id":"th_everlife","count":1,"reason":"可复活致命诅咒队友（永命，代价-25HP/本局）"},
  ],
  "nice":[
   {"id":"charged_strike","reason":"可选输出：充能打击（走纯暴击路线时）"},
   {"id":"full_focus","reason":"可选输出：集中（烈焰/冰封路线则放弃）"},
   {"id":"flaming_spirit","reason":"可选：烈焰之魂"},
   {"id":"frozen_heart","reason":"可选：冰封之心"},
   {"id":"poison_aspect","reason":"可选：毒素之相"},
   {"id":"iq_too_high","reason":"可选：智力过高"},
   {"id":"mass_aspect","reason":"可选生存：质量之相"},
   {"id":"healthy_guard","reason":"可选生存：健康守卫"},
   {"id":"featherweight","reason":"可选节奏：轻羽"},
   {"id":"quick_breath","reason":"可选节奏：快速呼吸"},
  ],
  "avoid":[],
  "playstyle":"攻速移速双修的综合奶：迅捷之手×7 加快治疗频率，极意×5 降低能量消耗。注意可选路线：抽到烈焰/冰封之魂改堆攻速；抽到充能打击改堆暴击。构筑由中文图鉴站生成，未验证，按实际情况灵活调整。",
  "reroll":""},
 {"classId":"thaumaturge","archetypeId":"biliheal","archetype":"奶妈进阶流（B站）","patch":"v0.51 (2026-07-29)","title":"攻速奶+分裂弹输出流","source":"B站视频《书奶（毒奶）玩法指导》（A_Soulsoul 07-21）+ 评论区 JohnUmane7 / JO丁 实测",
  "note":"视频口述（ASR转写）：通过造成伤害积累生命能量，伤害高低决定奶量效率——攻速是奶妈第一属性。分裂射击推荐点 1 个绝对不要 1 个以上（1弹140% / 2弹120%）；鹰眼 2 个抵消分裂散射；重手 1 个配分裂（双弹丸伤害×2）；永命 1 个就够；极意拿 3-6 层降消耗。评论补充（JohnUmane7）：攻速叠到 200，智商太高必拿有多少选多少，永恒生命看到必拿，火球必拿（点燃+中毒持续回蓝），大食汉多拿抵消负面，+50攻速传说和+75生命传说必拿。JO丁修正：弹速 3-4 级、射程 2-3 级、毒 1-2 级、强烈一击不拿（除非暴击符文）。",
  "must":[
   {"id":"swift_hands","count":10,"reason":"攻速叠到 200% 左右（JohnUmane7：'攻速手叠到200层就够'；视频：输出达标线=攻速200%+弹丸合计80伤害）"},
   {"id":"th_proficiency","count":3,"reason":"增加回复量并减少回复CD，越多越好（视频：'继援相关词条决定了奶距离和奶CD'）"},
   {"id":"th_keen_eye","count":3,"reason":"提升奶人手短距离，等级越高奶人距离越长；'一定要多拿距离！'（评论区）"},
   {"id":"th_mastery","count":6,"reason":"减少体力消耗，难出，看到优先拿；'点了三个满花板可以拿六磁降低消耗'（24%硬上限=8层）"},
   {"id":"th_splitshot","count":1,"reason":"**点 1 个绝对不要 1 个以上**：1弹伤害140%，2弹120%负收益（视频+JO丁一致）"},
   {"id":"eagle_eye","count":2,"reason":"弹速 3-4 级（JO丁）；鹰眼本身附带降低分裂散射，保中远距离命中"},
   {"id":"heavy_hand","count":1,"reason":"配分裂后双弹丸伤害直接变 200%，提升巨大；但不建议点多（-40%攻速需快手补回）"},
   {"id":"th_doping","count":1,"reason":"为被奶队友施加强谷（守护），点一次就够，多点提升BUFF时间"},
   {"id":"th_everlife","count":1,"reason":"复活黑骷髅队友的大级手段，看到必拿（JohnUmane7：'优先级比子弹还高'）；多个只减负面时间所以一个就够"},
   {"id":"iq_too_high","count":3,"reason":"智商太高了加 25 属性，奶妈打异常跟属性有关，'看到必拿，有多少选多少'（JohnUmane7）"},
   {"id":"flaming_spirit","count":1,"reason":"看见火球一定要拿：凤凰火的点燃会和中毒一起给你持续回蓝（评论区）"},
   {"id":"volatile_tenacity","count":1,"reason":"最后一波+不稳定韧性两个同时最好，只拿不稳定韧性也足够（视频）"},
  ],
  "nice":[
   {"id":"last_stand","reason":"配不稳定韧性：一血吸给击秒无敌（视频推荐双保险）"},
   {"id":"poison_aspect","count":1,"reason":"毒素项位可不点，最多 1 个（-15%被回复量难恢复；视频：'不推荐点，这度点一个'）"},
   {"id":"sticky","count":1,"reason":"抽到兴奋剂可以选，4秒守护扩到8秒无限叠加（JohnUmane7）"},
   {"id":"reactive_panic","count":1,"reason":"受伤加速，毒奶打近身有用，后期选（JohnUmane7）"},
   {"id":"benison_purification","count":1,"reason":"自动锁敌能喂奶充能，所有职业可用，推荐（JohnUmane7）"},
   {"id":"gluttonous","count":None,"reason":"抵消负面状态（毒/乌鸦减回复），可以多拿（JohnUmane7）"},
   {"id":"rapid_fire","count":1,"reason":"+50 攻速传说看到必拿（JohnUmane7）"},
   {"id":"mass_aspect","count":1,"reason":"+75 生命传说必拿，能少拿几个锁；拿到永命后专门多点HP词条（视频）"},
   {"id":"frozen_heart","count":1,"reason":"拿到传说白虎（冰封景象）可选，增加冰冻异常概率（JohnUmane7）"},
   {"id":"hawkeye","count":2,"reason":"射程 2-3 级（JO丁：为弥补分裂带来的散射）"},
   {"id":"fluffy","count":None,"reason":"拿到永命后多点提升HP的词条（视频）"},
   {"id":"smell_the_roses","count":1,"reason":"最终Boss超大AOE没有加速就必须保障能跑出范围（视频）"},
   {"id":"th_splashback","count":1,"reason":"治疗队友产生毒爆，可拿（JohnUmane7）"},
  ],
  "avoid":[
   {"id":"potent_strike","reason":"强烈一击是暴击才会增加异常概率，可以不拿（除非有暴击符文）（JO丁）"},
   {"id":"big_and_speedy","reason":"巨大急吸很强但必须补够防御，不然被锁定两三拳被打死（JO丁）"},
  ],
  "playstyle":"攻速奶：通过攻速快速叠生命能量→高频治疗。分裂弹1层+重手1层构成输出（双弹丸200%），鹰眼保证命中。双书奶才是完全体：一书奶负责奶人、一书奶负责输出，互不冲突（视频）。",
  "reroll":"一般3个商店都有奶妈能用的；中间/死神商店没刷好就看功能商店有没有攻速，优先推荐拿攻速（JohnUmane7）"},
 {"classId":"thaumaturge","archetypeId":"jpwiki","archetype":"稳定奶（日文wiki）","patch":"v0.51 (2026-07-29)","title":"稳定型远程奶妈（书奶）","source":"日文wiki build页（サウマタージビルド）",
  "note":"必须：锐眼7、熟练7、兴奋剂1、烈焰之灵1、鹰眼5、隼眼0-2、运动健将（MS140附近）；准必须：极意（见必拿）、溅射反冲、不稳定韧性/最后抵抗/健康守护、HP约200（导电护甲全拿、铁皮不要）、智力过高2；不要：分裂射击、永生。",
  "must":[
   {"id":"th_keen_eye","count":7,"reason":"Jim Phase2/3 远程奶防事故的必需射程；妥协可 6"},
   {"id":"th_proficiency","count":7,"reason":"奶量+CD 双核心（v0.51 CD缩短被削 15%→10%，更需要堆）"},
   {"id":"th_doping","count":1,"reason":"最强守护奶技，没抽到可考虑转生；v0.51 自我上限 3 层、CD+15%"},
   {"id":"flaming_spirit","count":1,"reason":"满血火球=回复资源获取最强（与寒冰之心互斥，冰版是降级）"},
   {"id":"eagle_eye","count":5,"reason":"弹速抵消智力过高惩罚；4 层保底"},
   {"id":"athletic","count":None,"reason":"移速堆到 140 附近（含暗号记录/其他来源），别开局多拿"},
  ],
  "nice":[
   {"id":"th_mastery","count":None,"reason":"能量消耗 -3%/层，24% 硬上限=8 层封顶；见必拿"},
   {"id":"th_splashback","count":None,"reason":"无代价 75 毒伤爆炸；近战队伍更赚"},
   {"id":"volatile_tenacity","count":1,"reason":"保命；配最后抵抗"},
   {"id":"last_stand","count":1,"reason":"配不稳定韧性；怕死选它"},
   {"id":"healthy_guard","count":1,"reason":"满血减伤+复活成本降半"},
   {"id":"conductive_armor","count":None,"reason":"物理防御+出血抗性（全拿）"},
   {"id":"iq_too_high","count":2,"reason":"元素 +25%/层；取 2 后补 1 迅捷之手"},
   {"id":"hawkeye","count":None,"reason":"0-2 层，鹰眼同用途"},
  ],
  "avoid":[
   {"id":"th_splitshot","reason":"1 层都别取：近战化+扩散，生存崩盘"},
   {"id":"th_everlife","reason":"复活代价=50秒废人+永久-25HP；理念冲突"},
   {"id":"poison_aspect","reason":"v0.51 受疗惩罚缓解但仍不建议"},
  ],
  "playstyle":"鹰眼+锐眼让你边打边看全场；痛苦交换的时机与目标选择是核心，差插奶的瞄准+血量判断能力要求高。",
  "reroll":"先看蓝（忍耐）绿（机动）→ 最后看红（时空）。红只在有必须传奇/奥义时才取；红只出伤害系就 reroll。必须项拿完前手动 reroll 只给红。青绿看到必须/准必须直接拿；拿完青绿必要数量后，红公共系补到需要数量再 reroll。伤害系多且必须项拿完→留 token 下轮。后期 HP 不稳可用绿 reroll。"},

 # ============ Nekomancer（猫灵师/猫奶） ============
 {"classId":"nekomancer","archetypeId":"codex","archetype":"召唤奶流（图鉴站）","patch":"v0.51","title":"灵魂召唤+生存强化流","source":"Ecliptica Codex 中文图鉴站构筑（36点规划）",
  "note":"常规：节奏=熟练、死之花、运动健将、练腿日；生存=不屈韧性、最后一搏、又大又圆、导电护甲、铁皮、蓬蓬、死灵契约。可选：输出/增益=冰封之心、烈焰之魂、怒焰诅咒、极意；生存=质量之相、健康守卫。",
  "must":[
   {"id":"athletic","count":8,"reason":"移速 +8%/层"},
   {"id":"nk_proficiency","count":8,"reason":"掉魂概率+随机灵魂生成（召唤核心）"},
   {"id":"fluffy","count":5,"reason":"最大生命 +10/层（猫灵师血量低，蓬蓬堆HP）"},
   {"id":"big_and_round","count":3,"reason":"击退抗性+最大生命"},
   {"id":"nk_death_blossom","count":3,"reason":"图腾猫治疗速度+范围（死之花，代价伤害-3%）"},
   {"id":"conductive_armor","count":2,"reason":"物理防御+出血抗性"},
   {"id":"shadow_aspect","count":2,"reason":"暗影伤害 +15%（暗影之相，配猫暗伤）"},
   {"id":"iron_skin","count":1,"reason":"防御 +8%"},
   {"id":"last_stand","count":1,"reason":"保命"},
   {"id":"volatile_tenacity","count":1,"reason":"保命"},
   {"id":"leg_day","count":1,"reason":"移速+跳高（练腿日）"},
   {"id":"nk_necropact","count":1,"reason":"低血量伤害转嫁猫（死灵契约）"},
  ],
  "nice":[
   {"id":"frozen_heart","reason":"可选输出/增益：冰封之心"},
   {"id":"flaming_spirit","reason":"可选输出/增益：烈焰之魂"},
   {"id":"curse_of_wrath","reason":"可选输出/增益：怒焰诅咒（愤怒诅咒）"},
   {"id":"nk_mastery","reason":"可选输出/增益：极意（每魂+伤害）"},
   {"id":"mass_aspect","reason":"可选生存：质量之相"},
   {"id":"healthy_guard","reason":"可选生存：健康守卫"},
  ],
  "avoid":[],
  "playstyle":"召唤奶流：熟练×8 保证灵魂产出，死之花强化图腾猫治疗；死灵契约+高HP构成生存底线。构筑由中文图鉴站生成，未验证，按实际情况灵活调整。",
  "reroll":""},
]
