# -*- coding: utf-8 -*-
# Ecliptica 数据 Part 4b: 职业专属升级 (Spellhammer / Shield Mage / Thaumaturge / Nekomancer)

CLASS_UP_SH = [
 {"id":"sh_prof_jump","en":"Spellhammer: Proficiency (Jump Smash)","jp":"スペルハンマー：熟練（ジャンプスマッシュ）","zh":"法锤士：熟练（跳砸）","rarity":"Common",
  "desc":"Knockback Force +10% (+10% per stack); Jump Smash Strength +5% (+5% per stack)","descZh":"击退力 +10%（每层+10%）；跳砸强度 +5%（每层+5%）","stack":"Linear",
  "tags":["dmg"],"base":55,
  "notes":"跳砸流基础强化。"},
 {"id":"sh_prof_chuck","en":"Spellhammer: Proficiency (Chuck)","jp":"スペルハンマー：熟練（投擲）","zh":"法锤士：熟练（投掷）","rarity":"Common",
  "desc":"Knockback Force +10%; Chucked Hammer Gravity Drop -10%; Additional explosion damage +8% (+8% per stack, v0.51)","descZh":"击退力 +10%；投掷锤重力衰减 -10%；额外爆炸伤害 +8%（每层+8%，v0.51 新增）","stack":"Linear",
  "tags":["dmg"],"base":65,
  "notes":"v0.51 新增爆炸伤害：锤本体+爆炸 2 段伤害。落锤（Chuck）流核心。"},
 {"id":"sh_boosted","en":"Spellhammer: Boosted","jp":"スペルハンマー：ブースト","zh":"法锤士：强化","rarity":"Rare",
  "desc":"Disperse Blast Strength +10%; Disperse Blast Damage +10%","descZh":"爆散（位移）强度 +10%；伤害 +10%","stack":"Linear",
  "tags":["utility","dmg"],"base":50,
  "notes":"位移技能（爆散）伤害与击退强化。"},
 {"id":"sh_mastery_jump","en":"Spellhammer: Mastery (Jump Smash)","jp":"スペルハンマー：極意（ジャンプスマッシュ）","zh":"法锤士：奥义（跳砸）","rarity":"Rare",
  "desc":"Landing Jump Smash on an enemy reduces its cooldown by 25% (X% per stack)","descZh":"跳砸命中敌人头顶时 CD -25%（每层+X%）","stack":"Hyperbolic",
  "tags":["dmg"],"base":60,
  "notes":"踩头减 CD 连段流核心；操作要求高。"},
 {"id":"sh_mastery_chuck","en":"Spellhammer: Mastery (Chuck)","jp":"スペルハンマー：極意（投擲）","zh":"法锤士：奥义（投掷）","rarity":"Rare",
  "desc":"Chucked Hammer bounces toward nearest enemy 1 time (+1 per stack); Gravity Drop -5%","descZh":"投掷锤着弹后向最近敌人弹跳 1 次（每层+1）；重力衰减 -5%","stack":"Linear",
  "tags":["dmg"],"base":70,
  "notes":"弹跳期间主/副手进入 CD；核爆锤玩法重要组件。"},
 {"id":"sh_concussion_jump","en":"Spellhammer: Concussion (Jump Smash)","jp":"スペルハンマー：脳震盪（ジャンプスマッシュ）","zh":"法锤士：震荡（跳砸）","rarity":"Legendary",
  "desc":"High-power Jump Smash deals additional ELECTRIC damage with 50% chance to PARALYZE","descZh":"高威力跳砸附加电伤害，50% 概率麻痹","stack":"Hyperbolic",
  "tags":["dmg"],"base":60,
  "notes":"麻痹控制流。"},
 {"id":"sh_concussion_chuck","en":"Spellhammer: Concussion (Chuck)","jp":"スペルハンマー：脳震盪（投擲）","zh":"法锤士：震荡（投掷）","rarity":"Legendary",
  "desc":"On successful hit, spawn an AoE dealing ELECTRIC damage with 50% chance to PARALYZE","descZh":"命中生成电伤害范围，50% 概率麻痹","stack":"Hyperbolic",
  "tags":["dmg"],"base":65,
  "notes":"AOE 电伤+麻痹。"},
 {"id":"sh_juggernaut_jump","en":"Spellhammer: Juggernaut (Jump Smash)","jp":"スペルハンマー：ジャガーノート（ジャンプスマッシュ）","zh":"法锤士：主宰（跳砸）","rarity":"Legendary",
  "desc":"High-power Jump Smash grants brief ENFORCED; max 5 stacks (+2 per upgrade)","descZh":"高威力跳砸获得短暂坚守；上限 5 层（每升级+2，v0.51 限制）","stack":"Linear",
  "tags":["defense"],"base":65,
  "notes":"v0.51 限制最大 5 层。跳砸流生存核心。"},
 {"id":"sh_juggernaut_chuck","en":"Spellhammer: Juggernaut (Chuck)","jp":"スペルハンマー：ジャガーノート（投擲）","zh":"法锤士：主宰（投掷）","rarity":"Legendary",
  "desc":"Full-power throw grants brief EMPOWERED; max 5 stacks of EMPOWERED (+2 per upgrade)","descZh":"满蓄力投掷获得短暂强力；强力上限 5 层（每升级+2）","stack":"Linear",
  "tags":["dmg"],"base":70,
  "notes":"核爆锤核心：蓄力投掷→强力增伤；配合重手/玻璃炮伤害爆炸。B站'一锤一锤核爆锤'。"},
]

CLASS_UP_SM = [
 {"id":"sm_proficiency","en":"Shieldmage: Proficiency","jp":"シールドメイジ：熟練","zh":"盾法师：熟练","rarity":"Common",
  "desc":"Defensive Stance shield range increased +?% (+?% per stack)","descZh":"防御姿态护盾范围 +?%（每层+?%）","stack":"Linear",
  "tags":["defense"],"base":70,
  "notes":"盾范围提升极大降低格挡难度；build 建议 2-3 层。10 层以上范围仍扩但收益低（日文实测）。"},
 {"id":"sm_unbreakable","en":"Shieldmage: Unbreakable","jp":"シールドメイジ：不壊","zh":"盾法师：不坏","rarity":"Common",
  "desc":"Purple damage -5% (-?% per stack); Evasive Maneuver purple reduction +10% (+?%); max reduction 75% including barrier","descZh":"紫伤害 -5%（每层）；离脱战术紫减免 +10%；含屏障最大减免 75%","stack":"Linear",
  "tags":["defense"],"base":85,
  "notes":"盾法师核心（build 必须 8-10 层）：紫攻击无法格挡只能靠减免。'不壊'。"},
 {"id":"sm_ice_burst","en":"Shieldmage: Ice Burst","jp":"シールドメイジ：アイスバースト","zh":"盾法师：寒冰爆发","rarity":"Rare",
  "desc":"Ice Burst charge gain increased +? (+? per stack)","descZh":"冰爆充能获取 +?（每层+?）","stack":"Linear",
  "tags":["dmg"],"base":45,
  "notes":"格挡充能→冰爆输出；需操作时机，build 推荐 1 层。"},
 {"id":"sm_mastery","en":"Shieldmage: Mastery","jp":"シールドメイジ：熟練（離脱戦術）","zh":"盾法师：奥义（离脱战术）","rarity":"Rare",
  "desc":"Evasive Maneuver shield size +50% (+?% per stack)","descZh":"离脱战术护罩范围 +50%（每层+?%）","stack":"Linear",
  "tags":["defense"],"base":50,
  "notes":"只保护队友的护罩扩大；太大易被敌人进入，勿多取。"},
 {"id":"sm_rally_up","en":"Shieldmage: Rally Up","jp":"シールドメイジ：結束","zh":"盾法师：集结","rarity":"Legendary",
  "desc":"Using Evasive Maneuver grants EMPOWERED stacks to self and allies within 35m","descZh":"使用离脱战术给自己与 35 米内队友强力","stack":"Linear",
  "tags":["dmg"],"base":60,
  "notes":"团队 DPS 提升；配 Warden 时范围 bug 变为无限（日文 wiki 提及）。"},
 {"id":"sm_warden","en":"Shieldmage: Warden","jp":"シールドメイジ：番人","zh":"盾法师：守望者","rarity":"Legendary",
  "desc":"Using Evasive Maneuver grants RESTORATION to self and all allies; Utility Cooldown +50% (+?% per stack, v0.51 100%→50%)","descZh":"使用离脱战术给自身与全体队友恢复；辅助 CD +50%（每层+X%，v0.51 由 100% 改 50%）","stack":"Linear",
  "tags":["healing"],"base":55,
  "notes":"v0.51 缓和（CD 惩罚 100%→50%），但日文 build 仍明确'非推奨'（CD+50% 依然太重）。恢复对紫攻击无效。"},
]

CLASS_UP_TH = [
 {"id":"th_keen_eye","en":"Thaumaturge: Keen Eye","jp":"サウマタージ：鋭い眼","zh":"咒术师：锐眼","rarity":"Common",
  "desc":"Pain Exchange range +15M (+15M per stack)","descZh":"痛苦交换射程 +15 米（每层+15）","stack":"Linear",
  "tags":["range"],"base":80,
  "notes":"书奶 build 必须 7 层（Jim Phase 2/3 远程奶防事故，可妥协 6）。后期敌人击退强，射程不足奶不到。"},
 {"id":"th_proficiency","en":"Thaumaturge: Proficiency","jp":"サウマタージ：熟練","zh":"咒术师：熟练","rarity":"Common",
  "desc":"Pain Exchange heal +3 HP (+3 per stack); Pain Exchange cooldown -10% (-10% per stack)","descZh":"痛苦交换治疗 +3 HP（每层+3）；CD -10%（每层-10%，v0.51 15%→10%）","stack":"Linear",
  "tags":["healing"],"base":85,
  "notes":"书奶 build 必须 7 层（v0.51 削弱 15%→10%，但仍核心）：奶量+CD 双收益。CD 有上限（-100% 封顶）。"},
 {"id":"th_mastery","en":"Thaumaturge: Mastery","jp":"サウマタージ：極意","zh":"咒术师：奥义","rarity":"Rare",
  "desc":"Pain Exchange energy cost -3% (-3% per stack)","descZh":"痛苦交换消耗能量 -3%（每层-3%；24% 硬上限，8 层封顶）","stack":"Linear",
  "tags":["healing"],"base":90,
  "notes":"书奶核心（'見かけたら必ず取っておこう'）：能量消耗降低=更多治疗循环。硬上限 24%（8 层）。"},
 {"id":"th_splitshot","en":"Thaumaturge: Splitshot","jp":"サウマタージ：スプリットショット","zh":"咒术师：分裂射击","rarity":"Rare",
  "desc":"Foul Pustule fires +1 projectile (+1 per stack); spread +2.5% (+2.5%, v0.51 fixed); damage -30% (-30% per stack)","descZh":"主手弹数 +1（每层+1）；扩散 +2.5%（每层，v0.51 修正）；伤害 -30%（每层-30%）","stack":"Linear",
  "tags":["dmg"],"base":25,
  "notes":"**书奶 build 明确'1 层都别取'**：变成近战喷子，交火距离骤降。扩散可用 Hawkeye 部分抵消（日文有完整期望值计算）。"},
 {"id":"th_doping","en":"Thaumaturge: Doping","jp":"サウマタージ：ドーピング","zh":"咒术师：兴奋剂","rarity":"Legendary",
  "desc":"Pain Exchange grants target 5 (+5 per stack) stacks of GUARDED; Pain Exchange cooldown +15% (+?% per stack, v0.51 silent change)","descZh":"痛苦交换为目标附加 5（每层+5）层守护；CD +15%（每层，v0.51 新增）；自我施加上限 3 层","stack":"Linear",
  "tags":["healing","defense"],"base":95,
  "notes":"书奶最强技能（'いわずとしれた強パーク'）：奶+守护双效。v0.51 限制：自我 buff 最大 3 层、守护有上限、CD+15%。没抽到可考虑转生重来。队友满血无法作为目标——需要'故意不满血'卡时机。"},
 {"id":"th_everlife","en":"Thaumaturge: Everlife","jp":"永遠の命","zh":"咒术师：永生","rarity":"Legendary",
  "desc":"Revive MORTAL CURSED players using 100% Life Energy; self gets BREACHED 42s (-7s) and WEAKENED 48s (-8s), -25 Max HP for the round; Life Energy gain -10% (-10% per stack)","descZh":"消耗 100% 生命能量复活被致命诅咒的队友；自身获得 42 秒破甲/48 秒虚弱，本局最大 HP -25；生命能量获取 -10%（每层）","stack":"Linear",
  "tags":["healing"],"base":40,
  "notes":"书奶 build 明确'不要'（'負けないようにするのがコンセプト'）：复活代价太大，约 50 秒无法有效治疗。高难局若治疗资源充足可考虑，重复取不划算。"},
 {"id":"th_splashback","en":"Thaumaturge: Splashback","jp":"サウマタージ：スプラッシュバック","zh":"咒术师：溅射反冲","rarity":"Legendary",
  "desc":"Pain Exchange target location spawns a POISON explosion dealing 75 damage","descZh":"痛苦交换目标点生成 75 伤害毒爆","stack":"Linear",
  "tags":["dmg"],"base":55,
  "notes":"无代价附加毒伤；近战多的队伍收益高。书奶 build'可有可无'。"},
]

CLASS_UP_NK = [
 {"id":"nk_proficiency","en":"Nekomancer: Proficiency","jp":"ネコマンサー：熟練","zh":"猫术士：熟练","rarity":"Common",
  "desc":"Killed enemies drop souls +5% (+?%); random soul appearance +25% (+?%)","descZh":"击杀掉魂概率 +5%（每层+X）；随机魂出现率 +25%（每层+X）","stack":"Linear",
  "tags":["summon"],"base":80,
  "notes":"猫术士核心（'キティが本体'）：没有足够的魂什么都干不了。4 层不保证常驻随机魂（基础概率倍率）。"},
 {"id":"nk_death_blossom","en":"Nekomancer: Death Blossom","jp":"ネコマンサー：デスブロッサム","zh":"猫术士：死亡绽放","rarity":"Rare",
  "desc":"Totem Kitty heal rate +10%; Totem Kitty effect range +1M; Overall Damage -3% per stack","descZh":"图腾猫治疗速率 +10%（每层）；范围 +1 米（每层）；总伤害 -3%（每层）","stack":"Linear",
  "tags":["healing","summon"],"base":60,
  "notes":"奶猫强化；-3% 总伤代价小，'見かけたら取ろう'（日文）。"},
 {"id":"nk_mastery","en":"Nekomancer: Mastery","jp":"ネコマンサー：極意","zh":"猫术士：奥义","rarity":"Rare",
  "desc":"Each soul held grants +2% Overall Damage (+?%); Health Regeneration +20% (+?%)","descZh":"每持有 1 魂 +2% 总伤害（每层+X）；自然回复 +20%（每层+X）","stack":"Linear",
  "tags":["dmg","summon"],"base":55,
  "notes":"与 Necropact（死之契约）相性极差（低血量机制冲突，日文 wiki 明确）。"},
 {"id":"nk_soul_detonation","en":"Nekomancer: Soul Detonation","jp":"ネコマンサー：ソウルデトネーション","zh":"猫术士：灵魂引爆","rarity":"Rare",
  "desc":"When Kitty dies, explode for ? SHADOW damage in 2m (+1.5m per stack) radius with 50% BREACHED chance","descZh":"猫死亡时 2 米（每层+1.5 米）范围暗影爆炸，50% 破甲","stack":"Linear",
  "tags":["dmg"],"base":50,
  "notes":"v0.51 爆炸半径改动；需要猫死在敌人身边，操作要求高。图腾猫配合更可行。"},
 {"id":"nk_necropact","en":"Nekomancer: Necropact","jp":"ネコマンサー：死の契約","zh":"猫术士：死亡契约","rarity":"Legendary",
  "desc":"While a Kitty is summoned, damage taken at LOW HP increased 600% and redirected to the Kitty","descZh":"召唤猫时，低血量受到的伤害增加 600% 并由猫承担","stack":"Linear",
  "tags":["survival"],"base":75,
  "notes":"低血量免死（猫扛伤）；与极意相性差（自然回复会脱离低血量）；配巨大且暴怒（Big and Wrathful）极佳（日文 wiki）。猫术士初始 HP 低，低血量前可能先死。"},
]
