# -*- coding: utf-8 -*-
# Ecliptica 数据 Part 2: Crystal of Mobility (机动商店) 18 技能

SHOP_MOB = [
 {"id":"athletic","en":"Athletic","jp":"アスレチック","zh":"运动健将","rarity":"Common",
  "desc":"Movement Speed: +8% (+8% per stack)","descZh":"移动速度 +8%（每层+8%）","stack":"Linear",
  "tags":["movespeed"],"base":65,
  "notes":"移速软上限 150%、硬上限 200%。Thaumaturge build 目标 MS 140 附近（含符文/加速等来源），堆到软上限后收益骤降。"},
 {"id":"eagle_eye","en":"Eagle Eye","jp":"イーグルアイ","zh":"鹰眼","rarity":"Common",
  "desc":"Projectile Speed +35% (+35% per stack)","descZh":"弹速 +35%（每层+35%）","stack":"Linear",
  "tags":["projectile"],"base":50,
  "notes":"远程/法系核心（弹速软上限 250%）。Thaumaturge build 必须 5 层以上（配合 IQ 太高了 的弹速惩罚）。近战职业价值低。"},
 {"id":"hawkeye","en":"Hawkeye","jp":"ホークアイ","zh":"隼眼","rarity":"Common",
  "desc":"Projectile Distance +10 M (+10 M per stack); Projectile Spread -1% (-1% per stack)","descZh":"射程 +10 米（每层+10）；弹道扩散 -1%（每层-1%）","stack":"Linear",
  "tags":["projectile"],"base":40,
  "notes":"射程与扩散；对狙击/远程流价值高，Thaumaturge 0-2 层即可。近战基本无用。"},
 {"id":"quick_breath","en":"Quick Breath","jp":"迅息","zh":"急促呼吸","rarity":"Common",
  "desc":"Utility Cooldown Rate: +10% (+10% per stack)","descZh":"辅助技能冷却速率 +10%（每层+10%）","stack":"Linear",
  "tags":["utility"],"base":50,
  "notes":"Utility CD 软上限 200% 硬上限 300%；依赖位移/辅助技能的职业（Spellsword/Spellhammer/Gunmancer）价值高。"},
 {"id":"springfoot","en":"Springfoot","jp":"跳躍力","zh":"弹簧脚","rarity":"Common",
  "desc":"Jump Height: +20% (+20% per stack)","descZh":"跳跃高度 +20%（每层+20%）","stack":"Linear",
  "tags":["jump"],"base":45,
  "notes":"Spellhammer 核心（Jump Smash 伤害随跳跃高度缩放）、Twinmage 空中流派；其他职业一般。"},
 {"id":"swift_hands","en":"Swift Hands","jp":"俊敏の手","zh":"迅捷之手","rarity":"Common",
  "desc":"Attack Speed: +15% (+15% per stack)","descZh":"攻击速度 +15%（每层+15%）","stack":"Linear",
  "tags":["attackspeed"],"base":75,
  "notes":"攻速软上限 250% 硬上限 400%。几乎所有输出职业的核心堆叠；B站社区：光法攻速拉到 200% 就够（再往上暴击率递减）。"},
 {"id":"leg_day","en":"Leg Day","jp":"今日は脚の集中トレーニング！","zh":"练腿日！","rarity":"Rare",
  "desc":"Reduces HEAVY stacks taken by X; Movement Speed +5% (+5% per stack); Jump Height +10% (+10% per stack)","descZh":"减少沉重层数；移速 +5%（每层+5%）；跳高 +10%（每层+10%）","stack":"Linear",
  "tags":["movespeed","jump"],"base":40,
  "notes":"移速+跳高双收益，数值不高但无副作用；Spellhammer 可用。"},
 {"id":"reactive_panic","en":"Reactive Panic","jp":"反射的パニック","zh":"应激恐慌","rarity":"Rare",
  "desc":"Taking damage grants 1 (+1 per stack) stack of FRENZIED","descZh":"受到伤害获得 1（每层+1）层狂乱","stack":"Linear",
  "tags":["frenzy"],"base":50,
  "notes":"狂乱提供攻速/移速；受伤触发，站在伤害地板上可快速叠层（日文 wiki 实测）。Twinmage/输出流可用。"},
 {"id":"smell_the_roses","en":"Smell the Roses","jp":"バラの香り","zh":"闻闻花香","rarity":"Rare",
  "desc":"Falling to low HP grants 7 (+2 per stack) stacks of HASTE with a 30s cooldown","descZh":"进入低血量获得 7（每层+2）层急速，30 秒冷却","stack":"Linear",
  "tags":["haste"],"base":40,
  "notes":"低血量保命跑路技；对脆皮输出有价值。"},
 {"id":"thunder_aura","en":"Thunder Aura","jp":"サンダーオーラ","zh":"雷霆光环","rarity":"Rare",
  "desc":"Every second inflict 25 (+X per stack) ELECTRIC damage to enemies in radius. Overall Damage -10% (-X% per stack); Movement Speed -5% (-X% per stack)","descZh":"每秒对周围敌人造成 25（每层+X）电伤害；总伤害 -10%（每层）；移速 -5%（每层）","stack":"Linear",
  "tags":["dmg"],"base":45,
  "notes":"AOE 蹭伤害；总伤害 -10% 是代价。盾奶 build 推荐 1-2 层（补输出+麻痹）。B站'受击雷霆'玩法核心。"},
 {"id":"berserker_soul_melee","en":"Berserker's Soul (Melee)","jp":"バーサーカーソウル","zh":"狂战士之魂（近战）","rarity":"Legendary",
  "desc":"Main attack damage grants Berserker's Soul stacks (up to X). Each stack: +X% Overall Damage, +X% Attack Speed, -X% Health Regeneration. Taking damage resets. Overall Damage -20% (-20% per stack); Attack Speed -40% (-40% per stack)","descZh":"主手攻击获得狂战士之魂层数（上限约 70 层）。每层 +0.64% 伤害、+1.28% 攻速、-0.71% 自然回复（近战）。受伤清空。自带 总伤害-20% 攻速-40%","stack":"Linear",
  "tags":["dmg","attackspeed"],"base":70,
  "notes":"v0.51 拆分近战/远程版本。满层约 +45% 伤害/+90% 攻速/-50% 自然回复。Dot 伤害不叠层；复取只加副作用。无伤流输出核心，'光法能一直无伤收益很高'（B站）。"},
 {"id":"berserker_soul_ranged","en":"Berserker's Soul (Ranged)","jp":"バーサーカーソウル","zh":"狂战士之魂（远程）","rarity":"Legendary",
  "desc":"Main attack damage grants Berserker's Soul stacks. Each stack: +X% Overall Damage, +X% Attack Speed, +X% Projectile Spread. Taking damage resets. Overall Damage -10% (-10% per stack); Attack Speed -20% (-20% per stack)","descZh":"主手攻击获得层数。每层 +0.64% 伤害、+1.28% 攻速、+0.02% 弹道扩散（远程）。受伤清空。自带 总伤害-10% 攻速-20%","stack":"Linear",
  "tags":["dmg","attackspeed"],"base":70,
  "notes":"远程版代价更轻（扩散可用 Hawkeye 抵消）。枪手/光法无伤流核心。"},
 {"id":"big_and_speedy","en":"Big and Speedy","jp":"巨大な休息","zh":"巨大且迅捷","rarity":"Legendary",
  "desc":"Utility Cooldown Rate +50% (+50% per stack); Overall Defense -20% (-20% per stack)","descZh":"辅助技能冷却速率 +50%（每层+50%）；总防御 -20%（每层-20%）","stack":"Linear",
  "tags":["utility"],"base":60,
  "notes":"盾奶 build 推荐 1 层（'巨大な急息'，提高仇恨获取节奏）；防御代价明显，坦克慎多取。"},
 {"id":"featherweight","en":"Featherweight","jp":"軽い足取り","zh":"轻盈步伐","rarity":"Legendary",
  "desc":"Movement Speed +30% (+30% per stack); Overall Defense -20% (-20% per stack)","descZh":"移速 +30%（每层+30%）；总防御 -20%（每层-20%）","stack":"Linear",
  "tags":["movespeed"],"base":50,
  "notes":"移速大提升但防御代价高；移速软上限 150% 注意溢出。输出/奶妈可选 1 层。"},
 {"id":"heavy_hand","en":"Heavy Hand","jp":"重撃","zh":"重手","rarity":"Legendary",
  "desc":"Damage +30% (+30% per stack); Attack Speed -40% (-40% per stack)","descZh":"伤害 +30%（每层+30%）；攻速 -40%（每层-40%）","stack":"Linear",
  "tags":["dmg"],"base":60,
  "notes":"与攻速流冲突；单发高伤职业（Spellhammer Chuck/跳砸、Gunmancer 蓄力）价值高。"},
 {"id":"partial_flight","en":"Partial Flight","jp":"短距離飛行","zh":"短暂飞行","rarity":"Legendary",
  "desc":"Extra Jump: +1 (+1 per stack)","descZh":"额外跳跃 +1（每层+1）","stack":"Linear",
  "tags":["jump"],"base":55,
  "notes":"二段跳极大改善走位与 Spellhammer 跳砸连段；通用强力技。"},
 {"id":"rapid_fire","en":"Rapid Fire","jp":"早撃ち","zh":"急速射击","rarity":"Legendary",
  "desc":"Attack Speed +50% (+50% per stack); Overall Damage -20% (-20% per stack)","descZh":"攻速 +50%（每层+50%）；总伤害 -20%（每层-20%）","stack":"Linear",
  "tags":["attackspeed"],"base":65,
  "notes":"攻速大户但总伤 -20%；攻速软上限 250% 前收益高，溢出后负收益。B站光法攻略：攻速拉到 200% 即可。"},
 {"id":"way_of_the_law","en":"Way of the Law","jp":"道路交通法","zh":"交通法规","rarity":"Legendary",
  "desc":"Periodically switch between STOP and GO status. STOP: reduced Movement/Attack Speed, increased Damage. GO: increased Movement/Attack Speed, decreased Damage","descZh":"周期切换 STOP/GO 状态：STOP 降速增伤，GO 增速降伤","stack":"Exponential",
  "tags":["dmg"],"base":35,
  "notes":"节奏不稳定，输出窗口随机；不推荐常规 build。"},
]
