# -*- coding: utf-8 -*-
# Ecliptica 数据 Part 7a: 流派 Build（真实网上攻略）
# 来源1: Ecliptica Codex 中文图鉴站 (omou.0862233.xyz, v0.51, 36点规划)
# 来源2: 日文wiki build页 (wikiwiki.jp)
# 每项技能带具体层数 count；nice=构筑"可选"分组（无固定层数）

BUILDS_A = [
 # ============ Spellsword（魔剑士） ============
 {"classId":"spellsword","archetypeId":"codex","archetype":"综合构筑（图鉴站）","patch":"v0.51","title":"近战攻击手：高机动+可观物理输出","source":"Ecliptica Codex 中文图鉴站构筑（36点规划）",
  "note":"常规：输出=迅捷之手、全力专注、力量、应激恐慌、熟练/爆发/破盾/旋风/极意、战意昂扬；生存=不屈韧性、最后一搏、铁皮、导电护甲、又大又圆、生命汲取、雷霆光环；节奏=快速呼吸、运动健将。可选：输出=绝境翻盘、充能打击；生存=蓬蓬、贪食者、质量之相；节奏=练腿日。",
  "must":[
   {"id":"strength","count":9,"reason":"物理伤害 +10%/层（构筑核心输出）"},
   {"id":"full_focus","count":5,"reason":"暴击率+暴伤；获得袖珍算盘时可节省点数"},
   {"id":"swift_hands","count":5,"reason":"攻速 +15%/层"},
   {"id":"quick_breath","count":4,"reason":"战术冷却 +10%/层"},
   {"id":"conductive_armor","count":1,"reason":"物理防御+出血抗性"},
   {"id":"iron_skin","count":1,"reason":"防御 +8%"},
   {"id":"big_and_round","count":1,"reason":"击退抗性+最大生命"},
   {"id":"last_stand","count":1,"reason":"低血量无敌保命"},
   {"id":"volatile_tenacity","count":1,"reason":"致命伤害存活"},
   {"id":"warriors_will","count":1,"reason":"战术技能叠赋能"},
   {"id":"athletic","count":1,"reason":"移速 +8%"},
   {"id":"reactive_panic","count":1,"reason":"受伤叠狂怒"},
   {"id":"ss_proficiency","count":1,"reason":"穿刺射程+狂怒叠层"},
   {"id":"ss_burst","count":1,"reason":"战术后攻速爆发"},
   {"id":"ss_mastery","count":1,"reason":"出血回血（代价自然回复-100%）"},
   {"id":"ss_shieldbreaker","count":1,"reason":"穿刺/斩击 +25% 伤害"},
   {"id":"ss_whirlwind","count":1,"reason":"满蓄力旋风持续伤害"},
  ],
  "nice":[
   {"id":"clutch_or_kick","reason":"可选输出：绝境翻盘"},
   {"id":"charged_strike","reason":"可选输出：充能打击"},
   {"id":"fluffy","reason":"可选生存：蓬蓬"},
   {"id":"gluttonous","reason":"可选生存：贪食者"},
   {"id":"mass_aspect","reason":"可选生存：质量之相"},
   {"id":"leg_day","reason":"可选节奏：练腿日"},
   {"id":"life_leech","reason":"构筑常规提及：生命汲取（可换雷霆光环）"},
   {"id":"thunder_aura","reason":"构筑常规提及：雷霆光环"},
  ],
  "avoid":[],
  "playstyle":"近战攻击手：高机动同时拥有可观的物理输出。构筑由中文图鉴站生成，未验证是否达到推荐水准，因游戏存在随机性，请根据实际情况合理取舍、灵活构筑。",
  "reroll":""},

 # ============ Twinmage（双生法师） ============
 {"classId":"twinmage","archetypeId":"codex","archetype":"综合构筑（图鉴站）","patch":"v0.51","title":"左手强化元素输出流","source":"Ecliptica Codex 中文图鉴站构筑（36点规划）",
  "note":"常规：输出=左势、极意、光辉之相、智力过高、法师精通、全力专注；生存=不屈韧性、最后一搏、铁皮、导电护甲、又大又圆、生命汲取、护佑；节奏=迅捷之手、鹰眼、运动健将、疾驰。可选：输出=充能打击+袖珍算盘、狂战士之魂（远程）、烈焰之魂、冰封之心；生存=蓬蓬、贪食者、健康守卫、质量之相；节奏=快速呼吸、练腿日、应激恐慌。",
  "must":[
   {"id":"tm_sinistra","count":9,"reason":"左手伤害/攻速 +5%/层（右手-3%）——主手元素强化核心"},
   {"id":"swift_hands","count":6,"reason":"攻速 +15%/层"},
   {"id":"full_focus","count":5,"reason":"暴击率+暴伤；配袖珍算盘可节省"},
   {"id":"vital_drain","count":3,"reason":"暴击回血"},
   {"id":"iq_too_high","count":3,"reason":"元素伤害 +25%/层（配鹰眼抵消弹速惩罚）"},
   {"id":"eagle_eye","count":2,"reason":"弹速 +35%/层"},
   {"id":"conductive_armor","count":1,"reason":"物理防御+出血抗性"},
   {"id":"iron_skin","count":1,"reason":"防御 +8%"},
   {"id":"big_and_round","count":1,"reason":"击退抗性+最大生命"},
   {"id":"last_stand","count":1,"reason":"保命"},
   {"id":"volatile_tenacity","count":1,"reason":"保命"},
   {"id":"luminous_aspect","count":1,"reason":"光耀伤害 +15%（光辉之相）"},
   {"id":"athletic","count":1,"reason":"移速 +8%"},
   {"id":"tm_guarded","count":1,"reason":"施加状态异常获得强化防御（护佑）"},
  ],
  "nice":[
   {"id":"charged_strike","reason":"可选：充能打击+袖珍算盘组合"},
   {"id":"pocket_abacus","reason":"可选：袖珍算盘（配充能打击）"},
   {"id":"berserker_soul_ranged","reason":"可选：狂战士之魂（远程）"},
   {"id":"flaming_spirit","reason":"可选：烈焰之魂"},
   {"id":"frozen_heart","reason":"可选：冰封之心"},
   {"id":"fluffy","reason":"可选生存：蓬蓬"},
   {"id":"gluttonous","reason":"可选生存：贪食者"},
   {"id":"healthy_guard","reason":"可选生存：健康守卫"},
   {"id":"mass_aspect","reason":"可选生存：质量之相"},
   {"id":"quick_breath","reason":"可选节奏：快速呼吸"},
   {"id":"leg_day","reason":"可选节奏：练腿日"},
   {"id":"reactive_panic","reason":"可选节奏：应激恐慌"},
   {"id":"tm_mastery","reason":"构筑常规：极意（技能伤害爆炸）"},
   {"id":"sorcerers_mastery","reason":"构筑常规：法师精通（元素伤害）"},
  ],
  "avoid":[],
  "playstyle":"主左手元素强化路线（左势×9 投入巨大，需明确主手元素）。构筑由中文图鉴站生成，未验证，按实际情况灵活调整。💡 光法（右手 Divine Hand 圣光手）路线参考——B站实测：'主要还是拉攻速，拉到200%就可以了；暴击异常可以小点几手；白蓝两个异常给buff都可以拿，金的道中可拿，对策Jim可带右手物法'（光法带飞视频评论区）；走光法时把左势换成右势（Dextra）、光之相（光辉之相）为核心。",
  "reroll":""},

 # ============ Gunmancer（枪术师） ============
 {"classId":"gunmancer","archetypeId":"codex","archetype":"综合构筑（图鉴站）","patch":"v0.51","title":"攻速暴击重炮流","source":"Ecliptica Codex 中文图鉴站构筑（36点规划）",
  "note":"常规：输出=熟练（光子）、迅捷之手、全力专注、智力过高、法师精通；生存=不屈韧性、最后一搏、铁皮、导电护甲、又大又圆、生命汲取；节奏=快速呼吸、运动健将、侧步。可选：输出=充能打击+袖珍算盘、法师精通、绝境翻盘、光辉之相、狂战士之魂（远程）；生存=蓬蓬、健康守卫、质量之相；节奏=快速呼吸、练腿日、应激恐慌。",
  "must":[
   {"id":"swift_hands","count":12,"reason":"攻速 +15%/层（构筑最大投入，蓄力/连射核心）"},
   {"id":"full_focus","count":5,"reason":"暴击率+暴伤"},
   {"id":"athletic","count":5,"reason":"移速 +8%/层"},
   {"id":"iq_too_high","count":4,"reason":"元素伤害 +25%/层"},
   {"id":"gm_sidestep","count":3,"reason":"气爆破冲刺获得加速（侧步）"},
   {"id":"conductive_armor","count":2,"reason":"物理防御+出血抗性"},
   {"id":"big_and_round","count":2,"reason":"击退抗性+最大生命"},
   {"id":"iron_skin","count":1,"reason":"防御 +8%"},
   {"id":"last_stand","count":1,"reason":"保命"},
   {"id":"volatile_tenacity","count":1,"reason":"保命"},
  ],
  "nice":[
   {"id":"gm_prof_photon","reason":"构筑常规：熟练（光子凝聚器）——光枪路线核心"},
   {"id":"sorcerers_mastery","reason":"构筑常规/可选：法师精通"},
   {"id":"charged_strike","reason":"可选：充能打击+袖珍算盘"},
   {"id":"pocket_abacus","reason":"可选：袖珍算盘"},
   {"id":"clutch_or_kick","reason":"可选：绝境翻盘"},
   {"id":"luminous_aspect","reason":"可选：光辉之相（圣光伤害）"},
   {"id":"berserker_soul_ranged","reason":"可选：狂战士之魂（远程）"},
   {"id":"fluffy","reason":"可选生存：蓬蓬"},
   {"id":"healthy_guard","reason":"可选生存：健康守卫"},
   {"id":"mass_aspect","reason":"可选生存：质量之相"},
   {"id":"quick_breath","reason":"可选节奏：快速呼吸"},
   {"id":"leg_day","reason":"可选节奏：练腿日"},
   {"id":"reactive_panic","reason":"可选节奏：应激恐慌"},
  ],
  "avoid":[],
  "playstyle":"攻速+暴击+元素伤害重炮流。构筑由中文图鉴站生成，未验证，按实际情况灵活调整。",
  "reroll":""},
 {"classId":"gunmancer","archetypeId":"bililightgun","archetype":"光枪流（B站）","patch":"v0.51 (2026-07-29)","title":"光属性重炮：Luminous 277% 实测天赋","source":"B站《光枪沉浸式输出三分半狂打20w+，到底是谁在诋毁光枪啊！》（UP 灵芝dayo，2026-07-12）+ 评论区天赋图与机制讨论",
  "must":[
   {"id":"swift_hands","count":10,"reason":"攻速 +15%/层，实机 192% 攻速——光枪 DPS 核心"},
   {"id":"iq_too_high","count":4,"reason":"全属性 +25%（评论：光枪熟练才 +7~8%，被 IQ 拉爆，是替代光枪熟练的正解）"},
   {"id":"luminous_aspect","count":3,"reason":"光属性形态核心——实机 Luminous Damage 277%，打暗弱点怪 20w+ 输出的来源"},
   {"id":"conductive_armor","count":3,"reason":"实机 Physical Defense 296%，站桩输出的生存保障"},
   {"id":"fluffy","count":2,"reason":"生命 +10/层，配合站桩输出防暴毙"},
   {"id":"glass_cannon","count":1,"reason":"总伤害 +35%（配高攻速收益最大）"},
   {"id":"sorcerers_mastery","count":1,"reason":"元素伤害 +8%"},
   {"id":"berserker_soul_ranged","count":1,"reason":"远程狂战魂：攻速大幅提升（站桩打法）"},
   {"id":"eagle_eye","count":1,"reason":"弹速提升，光枪手感"},
   {"id":"last_stand","count":1,"reason":"一血保命"},
   {"id":"life_leech","count":1,"reason":"吸血续航"},
   {"id":"big_and_round","count":1,"reason":"击退抗性 +50%，站桩不被推走"},
   {"id":"warriors_will","count":1,"reason":"伤害 +25%（战士意志）"},
   {"id":"clutch_or_kick","count":1,"reason":"随机高收益大天赋"},
   {"id":"volatile_tenacity","count":1,"reason":"不稳定韧性保命"},
   {"id":"vitality","count":1,"reason":"生命 +25"},
   {"id":"pocket_abacus","count":1,"reason":"点数计算/暴击联动"},
  ],
  "nice":[],
  "avoid":[
   {"id":"gm_prof_antimatter","reason":"光枪熟练不加：shift 飞天太慢反而降 DPS，属性伤害 +7~8% 被 IQ 太高（+25%）完爆（评论区 yohane_bili 机制分析）"},
  ],
  "playstyle":"站桩光炮流：核心是 Luminous 光属性伤害（实机 277%）+ 攻速（192%）——天赋图来源玩家实测 3 分半狂打 20w+ 输出。注意点：不点光枪熟练（shift 空中射击降 DPS）、暴击率仅 2%（不堆暴击，纯光伤碾压）；配 4 件神器：加密档案×3、轮回之轮×6、HC 装甲板×2、太阳圣杯×1（天赋图右下，跨小局累积）。来源：B站 灵芝dayo 光枪输出视频 + 评论区天赋图（灵芝dayo 分享，2026-07-13）。",
  "reroll":""},
 {"classId":"gunmancer","archetypeId":"bilidualgun","archetype":"双枪流（B站）","patch":"v0.51 (2026-07-29)","title":"镭射+散弹双枪流","source":"B站评论区 JO丁 实测分享（《最终BOSS通关建议》视频评论区）",
  "note":"玩家实测：双枪bug——按住左键，然后蓄力右键，只松右键可以镭射散弹一起打出。加点：散弹+3、有乌鸦点乌鸦、没乌鸦就点属性伤害+8、异常增加点出2、补攻速到150以上、战士的意志1级、暴击叠到27、暴击会爆炸的词条、不怂可以拿玻璃大炮/重击。实战数据：打弱暗的大螃蟹一颗散弹60、暴击100（战士意志1.25倍+易伤1.25倍），射手技能可给一次双倍伤害射击。光法数值偏低且最终不弱圣，前期弱圣怪少。",
  "must":[
   {"id":"gm_prof_firebomb","count":3,"reason":"散弹＋3（核心输出词条）"},
   {"id":"iq_too_high","count":2,"reason":"有乌鸦点乌鸦（元素伤害+25%/层）"},
   {"id":"sorcerers_mastery","count":3,"reason":"没乌鸦就点属性伤害＋8（法师精通）"},
   {"id":"swift_hands","count":8,"reason":"补攻速到 150 以上"},
   {"id":"warriors_will","count":1,"reason":"战士的意志 1 级（1.25倍伤害buff）"},
   {"id":"full_focus","count":5,"reason":"暴击叠到 27（全力专注约5层）"},
   {"id":"charged_strike","count":1,"reason":"暴击会爆炸的词条"},
   {"id":"gm_mastery","count":1,"reason":"射手技能可以给一次双倍伤害的射击（奥义）"},
  ],
  "nice":[
   {"id":"glass_cannon","count":1,"reason":"不怂可以拿玻璃大炮"},
   {"id":"heavy_hand","count":1,"reason":"重击（单发高伤流适配）"},
   {"id":"sticky","count":1,"reason":"异常增加点出 2（粘着性/异常词条）"},
   {"id":"potent_strike","count":1,"reason":"异常增加点出 2（强烈一击，暴击流可用）"},
   {"id":"volatile_tenacity","count":1,"reason":"保命"},
   {"id":"last_stand","count":1,"reason":"保命"},
   {"id":"conductive_armor","count":1,"reason":"生存补强"},
  ],
  "avoid":[
   {"id":"luminous_aspect","reason":"光法数值偏低且最终不弱圣，前期弱圣怪很少（JO丁实测）"},
   {"id":"springfoot","reason":"枪手跳跃流收益低"},
  ],
  "playstyle":"双枪：按住左键蓄力右键，只松右键可镭射+散弹同时打出（当前版本bug/技巧）。散弹+3 为主输出，攻速150+保证频率，暴击27%触发爆炸词条。单发高伤+战士意志+易伤构成爆发。",
  "reroll":"优先商店找散弹熟练/乌鸦/攻速；传说找战士意志/充能打击/玻璃炮/重手。"},

 # ============ Fistmage（拳法师） ============
 {"classId":"fistmage","archetypeId":"codex","archetype":"综合构筑（图鉴站）","patch":"v0.51","title":"格挡狂怒爆发流","source":"Ecliptica Codex 中文图鉴站构筑（36点规划）",
  "note":"常规：输出=力量、应激恐慌、狂怒、熟练、极意；生存=不屈韧性、最后一搏、又大又圆、导电护甲、铁皮；节奏=快速呼吸、疾跑、运动健将。可选：输出=绝境翻盘、施力；生存=蓬蓬、贪食者、生命力、质量之相；节奏=练腿日、又大又快。",
  "must":[
   {"id":"strength","count":10,"reason":"物理伤害 +10%/层（核心输出）"},
   {"id":"athletic","count":7,"reason":"移速 +8%/层（联动音速拳增伤）"},
   {"id":"fm_proficiency","count":4,"reason":"格挡回血+治疗光环"},
   {"id":"conductive_armor","count":2,"reason":"物理防御+出血抗性"},
   {"id":"big_and_round","count":2,"reason":"击退抗性+最大生命"},
   {"id":"fm_runner","count":2,"reason":"蓄力期间移速提升（疾跑）"},
   {"id":"fm_rage","count":2,"reason":"格挡后攻速 +100% 4秒+加速（狂怒）"},
   {"id":"fm_mach_punch","count":2,"reason":"超过100%移速按25%增伤（音速拳）"},
   {"id":"iron_skin","count":1,"reason":"防御 +8%"},
   {"id":"last_stand","count":1,"reason":"保命"},
   {"id":"volatile_tenacity","count":1,"reason":"保命"},
   {"id":"reactive_panic","count":1,"reason":"受伤叠狂怒"},
   {"id":"fm_mastery","count":1,"reason":"格挡获得赋能+强化防御（极意）"},
  ],
  "nice":[
   {"id":"clutch_or_kick","reason":"可选输出：绝境翻盘"},
   {"id":"fm_apply_force","reason":"可选输出：施力（格挡发射投射物）"},
   {"id":"fluffy","reason":"可选生存：蓬蓬"},
   {"id":"gluttonous","reason":"可选生存：贪食者"},
   {"id":"vitality","reason":"可选生存：生命力"},
   {"id":"mass_aspect","reason":"可选生存：质量之相"},
   {"id":"leg_day","reason":"可选节奏：练腿日"},
   {"id":"big_and_speedy","reason":"可选节奏：又大又快"},
  ],
  "avoid":[],
  "playstyle":"格挡是核心：熟练回血、狂怒爆发、极意叠buff；移速联动音速拳增伤。构筑由中文图鉴站生成，未验证，按实际情况灵活调整。",
  "reroll":""},
]
