# -*- coding: utf-8 -*-
# Ecliptica 数据 Part 4a: 职业专属升级 (Spellsword / Twinmage / Gunmancer / Fistmage)
# 字段: id, en, jp, zh, rarity, desc, descZh, stack, tags, base, notes

CLASS_UP_SS = [
 {"id":"ss_proficiency","en":"Spellsword: Proficiency","jp":"スペルソード：熟練","zh":"剑术家：熟练","rarity":"Common",
  "desc":"Piercing Strike range +4M (+4M per stack); Primary hits have 2.5% chance to grant FRENZIED (+? per stack)","descZh":"穿刺打击射程 +4 米（每层+4）；主手命中 2.5% 概率获得狂乱（v0.51 新增）","stack":"Linear",
  "tags":["range"],"base":65,
  "notes":"v0.51：主手命中 2.5% 概率叠狂乱（最大 5 层，加算时长）。后期需要拉距离，尽量取。"},
 {"id":"ss_mastery","en":"Spellsword: Mastery","jp":"スペルソード：極意","zh":"剑术家：奥义","rarity":"Rare",
  "desc":"Bleeding damage heals 2 HP (+? per stack); Health Regeneration -100% (-?% per stack)","descZh":"出血伤害回 2 HP（每层+1→v0.51 改为 1→2）；自然回复 -100%（v0.51 新增）","stack":"Linear",
  "tags":["lifesteal","status"],"base":75,
  "notes":"v0.51 改动：回血 1→2，新增自然回复 -100%。配 Cutting Edge 出血流；取 3 层左右，对多个敌人挂出血回复可观。Boss 战小伤恢复也有用。"},
 {"id":"ss_burst","en":"Spellsword: Burst","jp":"スペルソード：バースト","zh":"剑术家：爆发","rarity":"Rare",
  "desc":"Using Utility skill grants +50% Attack Speed for 3 seconds (+50% per stack); Utility Cooldown +20% (+20% per stack)","descZh":"使用位移技能后 3 秒攻速 +50%（每层+50%）；位移 CD +20%（每层+20%）","stack":"Linear",
  "tags":["attackspeed"],"base":60,
  "notes":"强力但代价大；可与攻速上限叠加（Frenzied/Burst 可突破攻速上限）。"},
 {"id":"ss_swift_stab","en":"Spellsword: Swift Stab","jp":"スペルソード：素早い一突き","zh":"剑术家：迅捷突刺","rarity":"Legendary",
  "desc":"Piercing Strike damage +35% (+35% per stack) multiplied by Movement Speed over 100%","descZh":"穿刺打击伤害按超过 100% 的移速比例 +35%（每层+35%）乘算","stack":"Linear",
  "tags":["dmg","movespeed"],"base":80,
  "notes":"无副作用，移速越高收益越大；剑术家核心输出升级，优先取。"},
 {"id":"ss_shieldbreaker","en":"Spellsword: Shieldbreaker","jp":"スペルソード：シールドブレイカー","zh":"剑术家：破盾者","rarity":"Legendary",
  "desc":"Piercing Strike deals 25% damage to BLOCKING enemies (+?%); Telekinetic Strike base damage +25% (+?%)","descZh":"穿刺对格挡敌人造成 25% 伤害（每层+X）；念力斩基础伤害 +25%（v0.51 新增）","stack":"Linear",
  "tags":["dmg"],"base":50,
  "notes":"v0.51 新增：若为念力斩则追加 25% 伤害。目前会完全格挡的 boss 不多，日文 wiki 评价'微妙'。"},
 {"id":"ss_whirlwind","en":"Spellsword: Whirlwind","jp":"スペルソード：旋風","zh":"剑术家：旋风","rarity":"Legendary",
  "desc":"Full-charge Piercing Strike fires a spherical whirlwind dealing continuous PHYSICAL damage, piercing enemies; Piercing Strike charge time +10% (+10% per stack)","descZh":"满蓄力穿刺发射球状旋风，穿透敌人持续物理伤害；蓄力时间 +10%（每层+10%）","stack":"Linear",
  "tags":["dmg"],"base":85,
  "notes":"彻底改变玩法的远程化升级：约 0.1 秒一跳，大型敌人伤害爆炸；继承出血概率（配极意极强）；旋风暴击判定无效（暴击流不适用）。v0.51 后出血回血翻倍使其更强。"},
]

CLASS_UP_TM = [
 {"id":"tm_sinistra","en":"Twinmage: Sinistra","jp":"ツインメイジ：シニストラ","zh":"双法师：左手（Sinistra）","rarity":"Common",
  "desc":"Left hand damage +5% (+5% per stack); Left hand attack speed +5%; Right hand damage -3%; Right hand attack speed -3%","descZh":"左手伤害/攻速 +5%（每层+5%）；右手伤害/攻速 -3%（每层-3%）","stack":"Linear",
  "tags":["dmg"],"base":55,
  "notes":"左右手取舍：主手（常用元素）强化。计算组 B（与普通增伤乘算）。"},
 {"id":"tm_dextra","en":"Twinmage: Dextra","jp":"ツインメイジ：デクストラ","zh":"双法师：右手（Dextra）","rarity":"Common",
  "desc":"Right hand damage +5% (+5% per stack); Right hand attack speed +5%; Left hand damage -3%; Left hand attack speed -3%","descZh":"右手伤害/攻速 +5%（每层+5%）；左手伤害/攻速 -3%（每层-3%）","stack":"Linear",
  "tags":["dmg"],"base":55,
  "notes":"与 Sinistra 对应：双元素流时取舍。光法（Divine Hand）走右手则 Dextra。"},
 {"id":"tm_proficiency","en":"Twinmage: Proficiency","jp":"ツインメイジ：熟練","zh":"双法师：熟练","rarity":"Common",
  "desc":"Quickwarp distance +3M (+3M per stack)","descZh":"瞬移距离 +3 米（每层+3）","stack":"Linear",
  "tags":["utility"],"base":50,
  "notes":"位移距离提升；双法师 CD 略长，一次瞬移更远有价值。"},
 {"id":"tm_rush","en":"Twinmage: Rush","jp":"ツインメイジ：ラッシュ","zh":"双法师：疾冲","rarity":"Common",
  "desc":"Inflicting a status effect grants 4 (+2 per stack) stacks of HASTE","descZh":"施加状态异常获得 4（每层+2）层急速","stack":"Linear",
  "tags":["haste","status"],"base":45,
  "notes":"异常触发不稳定（异常有冷却且概率低），日文 wiki 评价'评价難しい'。"},
 {"id":"tm_guarded","en":"Twinmage: Guarded","jp":"ツインメイジ：守護","zh":"双法师：守护","rarity":"Rare",
  "desc":"Inflicting a status effect grants 4 (+2 per stack) stacks of GUARDED","descZh":"施加状态异常获得 4（每层+2）层守护","stack":"Linear",
  "tags":["status","defense"],"base":45,
  "notes":"异常触发不稳定，同 Rush。"},
 {"id":"tm_mastery","en":"Twinmage: Mastery","jp":"ツインメイジ：極意","zh":"双法师：奥义","rarity":"Rare",
  "desc":"Dealing skill damage triggers an explosion dealing 25% damage in radius ?M (+?M per stack)","descZh":"技能伤害触发 25% 伤害爆炸（半径每层+X）","stack":"Linear",
  "tags":["dmg"],"base":80,
  "notes":"简单强力的 +25% 增伤；2 层以上收益薄（日文 wiki 注意）。核心输出升级。"},
 {"id":"tm_wicked_sign","en":"Twinmage: Wicked Sign","jp":"ツインメイジ：邪悪な兆","zh":"双法师：凶兆","rarity":"Rare",
  "desc":"Using Utility skill has 6.7% (+?% per stack) chance to grant 7 stacks of EMPOWERED/GUARDED/HASTE/FRENZIED. 100% chance at 67 HP","descZh":"使用位移技能 6.7%（每层+X%）概率获得强力/守护/急速/狂乱各 7 层；HP 为 67 时 100%","stack":"Linear",
  "tags":["utility"],"base":70,
  "notes":"离谱 buff 池；主动触发需放弃位移 CD 的应急价值。上限 67 HP 机制特殊。"},
 {"id":"tm_retaliation","en":"Twinmage: Retaliation","jp":"ツインメイジ：報復","zh":"双法师：报复","rarity":"Legendary",
  "desc":"Taking damage of the same element as your skill grants 3 stacks of EMPOWERED","descZh":"受到与技能同属性的伤害时获得 3 层强力","stack":"Linear",
  "tags":["defense"],"base":40,
  "notes":"需要挨打触发，收益一般，日文 wiki 评价'必要性薄い'。"},
]

CLASS_UP_GM = [
 {"id":"gm_overcharged","en":"Gunmancer: Overcharged (VA-11 Blast Cannon)","jp":"ガンマンサー：オーバーチャージ（VA-11ブラスト砲）","zh":"枪术士：过载（VA-11 爆能炮）","rarity":"Common",
  "desc":"Projectile size +5% (+5% per stack); ELECTRIC damage +15% (+15% per stack)","descZh":"弹体大小 +5%（每层+5%）；电伤害 +15%（每层+15%）","stack":"Linear",
  "tags":["dmg"],"base":55,
  "notes":"电枪（VA-11）强化；弹体变大更易命中。"},
 {"id":"gm_prof_firebomb","en":"Gunmancer: Proficiency (Firebomb)","jp":"ガンマンサー：熟練（爆炎弾）","zh":"枪术士：熟练（爆炎弹）","rarity":"Common",
  "desc":"Explosion radius +1M (+1M per stack); FIRE damage +7% (+7% per stack)","descZh":"爆炸半径 +1 米（每层+1）；火伤 +7%（每层+7%）","stack":"Linear",
  "tags":["dmg"],"base":55,
  "notes":"喷子（爆炎弹）流强化。"},
 {"id":"gm_prof_photon","en":"Gunmancer: Proficiency (Photon Condenser)","jp":"ガンマンサー：熟練（フォトン・コンデンサー）","zh":"枪术士：熟练（光子凝聚器）","rarity":"Common",
  "desc":"Charged shot fires +2 projectiles (+2 per stack); LUMINOUS damage +7% (+7% per stack)","descZh":"蓄力射击弹数 +2（每层+2，v0.51 由 +1 改 +2）；圣光伤害 +7%（每层+7%）","stack":"Linear",
  "tags":["dmg"],"base":70,
  "notes":"v0.51 加强（+1→+2）；注意弹数加成只对'使用位移技能后的蓄力射击'生效。光枪（VA-11/光子）流核心。"},
 {"id":"gm_prof_antimatter","en":"Gunmancer: Proficiency (Antimatter Accelerator)","jp":"ガンマンサー：熟練（アンチマター・アクセラレーター）","zh":"枪术士：熟练（反物质加速器）","rarity":"Common",
  "desc":"Projectiles +1 (+1 per stack); SHADOW damage +7% (+7% per stack)","descZh":"弹数 +1（每层+1）；暗影伤害 +7%（每层+7%）","stack":"Linear",
  "tags":["dmg"],"base":65,
  "notes":"暗枪（反物质）流强化。"},
 {"id":"gm_sidestep","en":"Gunmancer: Sidestep","jp":"ガンマンサー：サイドステップ","zh":"枪术士：侧步","rarity":"Common",
  "desc":"Using Airblast grants 2 stacks of HASTE","descZh":"使用空气冲击获得 2 层急速","stack":"Linear",
  "tags":["haste"],"base":55,
  "notes":"2 层可常驻 buff；3 层以上几乎无收益（时长加算上限 5 层）。"},
 {"id":"gm_marksman","en":"Gunmancer: Marksman (VA-11 Blast Cannon)","jp":"ガンマンサー：マークスマン（VA-11ブラスト砲）","zh":"枪术士：神射手（VA-11 爆能炮）","rarity":"Legendary",
  "desc":"Every 10s a coin is thrown; shooting it with VA-11 fires an explosion with 400% damage toward nearby enemies (coin size +10%)","descZh":"每 10 秒投掷硬币，用 VA-11 射击硬币向附近敌人释放 400% 伤害爆炸（硬币大小 +10%）","stack":"Linear",
  "tags":["dmg"],"base":60,
  "notes":"机制特殊：本体弹被硬币吸收，实际收益约 1.66 倍（弹+爆炸）；换技能打硬币会空耗。光枪玩家可玩。"},
 {"id":"gm_mastery","en":"Gunmancer: Mastery","jp":"ガンマンサー：極意","zh":"枪术士：奥义","rarity":"Legendary",
  "desc":"Charged shot damage +50% (+50% per stack)","descZh":"蓄力射击伤害 +50%（每层+50%）","stack":"Linear",
  "tags":["dmg"],"base":75,
  "notes":"蓄力射击指位移技能后高空'シャキン'音效后使用的主/副手技能；光枪核心输出。"},
]

CLASS_UP_FM = [
 {"id":"fm_proficiency","en":"Fistmage: Proficiency","jp":"フィストメイジ：熟練","zh":"拳法师：熟练","rarity":"Common",
  "desc":"Successful parry heals 2 HP (+2 per stack) and creates an aura healing allies for half","descZh":"格挡成功回 2 HP（每层+2）并产生光环治疗周围队友一半","stack":"Linear",
  "tags":["lifesteal","healing"],"base":70,
  "notes":"格挡流核心；自回+团队光环。"},
 {"id":"fm_mach_punch","en":"Fistmage: Mach Punch","jp":"フィストメイジ：マッハパンチ","zh":"拳法师：马赫拳","rarity":"Rare",
  "desc":"PHYSICAL damage increased by 25% of Movement Speed over 100%","descZh":"超过 100% 的移速按 25% 比例增加物理伤害","stack":"Linear",
  "tags":["dmg","movespeed"],"base":65,
  "notes":"移速流增伤；配 Athletic/Featherweight。"},
 {"id":"fm_mastery","en":"Fistmage: Mastery","jp":"フィストメイジ：極意","zh":"拳法师：奥义","rarity":"Rare",
  "desc":"Successful parry grants +1 (+1 per stack) stack of EMPOWERED and GUARDED","descZh":"格挡成功获得强力/守护各 1（每层+1）层","stack":"Linear",
  "tags":["status"],"base":65,
  "notes":"格挡后 buff；叠层越多越强。"},
 {"id":"fm_rage","en":"Fistmage: Rage","jp":"フィストメイジ：激昂","zh":"拳法师：激昂","rarity":"Rare",
  "desc":"Successful parry grants 100% Attack Speed for 4s and 3 (+1 per stack) HASTE. Max 10 (+2 per stack) stacks","descZh":"格挡成功 4 秒攻速 +100% 并获得 3（每层+1）层急速；急速上限 10（每层+2，v0.51 改动）","stack":"Linear",
  "tags":["attackspeed"],"base":75,
  "notes":"v0.51：急速最大 10 层起，每升级 +2。攻速×激昂乘算，爆发极高。拳法师核心。"},
 {"id":"fm_runner","en":"Fistmage: Runner","jp":"フィストメイジ：ランナー","zh":"拳法师：跑者","rarity":"Rare",
  "desc":"While charging primary, Movement Speed gradually increases","descZh":"蓄力主手时移速逐渐提升（v0.51 叠乘倍率下调）","stack":"Linear",
  "tags":["movespeed"],"base":50,
  "notes":"v0.51 削弱（倍率降低）。"},
 {"id":"fm_apply_force","en":"Fistmage: Apply Force","jp":"フィストメイジ：力の付与","zh":"拳法师：施加力量","rarity":"Legendary",
  "desc":"Successful parry grants 1 (+? per stack) Apply Force stack. While stacked, charged primary fires a PHYSICAL projectile consuming 1 stack. Parry cooldown +30% (+?%)","descZh":"格挡成功获得 1（每层+X）层力量；有层时蓄力主手发射物理投射物消耗 1 层；格挡 CD +30%","stack":"Linear",
  "tags":["dmg"],"base":70,
  "notes":"格挡→远程投射物；核心输出升级，代价是格挡 CD。"},
]
