# -*- coding: utf-8 -*-
# Ecliptica 数据 Part 1: Crystal of Perseverance (生存商店) 24 技能
# base: 0-100 通用基准分; tags: 属性标签; mutual: 互斥; prio: 职业覆盖 {classId: score}

SHOP_PERS = [
 {"id":"fluffy","en":"Fluffy","jp":"ふわふわ","zh":"毛茸茸","rarity":"Common",
  "desc":"Max HP: +10 (+10 per stack)","descZh":"最大生命 +10（每层+10）","stack":"Linear",
  "tags":["hp"],"base":70,
  "notes":"最通用的生存向堆叠技能；后期 HP 溢出时可适量补。坦位（Fistmage/Shield Mage）核心堆叠项。"},
 {"id":"gluttonous","en":"Gluttonous","jp":"大食漢","zh":"大胃王","rarity":"Common",
  "desc":"Received Healing +5% (+5% per stack)","descZh":"受到治疗 +5%（每层+5%）","stack":"Linear",
  "tags":["healing"],"base":55,
  "notes":"受疗加成（含奶妈给的奶），自身自然回血不受影响；对依赖治疗的坦/输出都有价值。"},
 {"id":"sacrificial_lamb","en":"Sacrificial Lamb","jp":"生贄の羊","zh":"献祭羔羊","rarity":"Common",
  "desc":"Upon dying, heal every other party member by 15 HP (+15 HP per stack)","descZh":"死亡时治疗其他队友 15 HP（每层+15）","stack":"Linear",
  "tags":["healing"],"base":20,
  "notes":"单排（solo）不会出现；仅死亡收益，常规局价值低，除非有自爆/送死流。"},
 {"id":"swarm_enforcer","en":"Swarm Enforcer","jp":"群れの用心棒","zh":"群聚保镖","rarity":"Common",
  "desc":"Gain +1.5% Defense for each enemy within 32 meters of you (+1.5% per stack)","descZh":"32 米内每名敌人提供 +1.5% 防御（每层+1.5%）","stack":"Linear",
  "tags":["defense"],"base":45,
  "notes":"小怪波次收益极高，boss 战仅 1 个目标时收益低；清怪快的队伍收益有限。"},
 {"id":"vitality","en":"Vitality","jp":"活力","zh":"活力","rarity":"Common",
  "desc":"Health Regeneration: +80% (+80% per stack)","descZh":"自然回复 +80%（每层+80%）","stack":"Linear",
  "tags":["regen"],"base":65,
  "notes":"自然回血是全体通用恢复手段；对坦与持续战斗职业价值最高，配合 Big and Lazy 效果翻倍。"},
 {"id":"vital_drain","en":"Vital Drain","jp":"バイタルドレイン","zh":"生命虹吸","rarity":"Common",
  "desc":"Critical strikes recover 2 HP (+2 HP per stack)","descZh":"暴击回复 2 HP（每层+2）","stack":"Linear",
  "tags":["lifesteal","crit"],"base":50,
  "notes":"不吃受疗加成；高频攻击/暴击流职业收益高，法系与枪手价值高。"},
 {"id":"adrenaline_fiend","en":"Adrenaline Fiend","jp":"アドレナリン中毒者","zh":"肾上腺素成瘾","rarity":"Rare",
  "desc":"Using your Utility skill recovers 6 (+6 per stack) HP; Utility Cooldown Rate +7% (+7% per stack); Received Healing -15% (-15% per stack)","descZh":"使用位移/辅助技能回 6 HP（每层+6）；辅助技能 CD 速率 +7%（每层+7%）；受疗 -15%（每层-15%）","stack":"Linear",
  "tags":["healing","utility"],"base":40,
  "notes":"需要频繁使用 Utility 的职业收益高；受疗 -15% 会稀释 Gluttonous，注意平衡。"},
 {"id":"big_and_lazy","en":"Big and Lazy","jp":"巨大な怠惰","zh":"巨大且懒惰","rarity":"Rare",
  "desc":"When standing still for at least 1 second, gain 200% (+50% per stack) extra Health Regeneration. When moving, set Health Regeneration to 0%.","descZh":"站立 1 秒以上获得额外 200%（每层+50%）自然回复；移动时自然回复归零。","stack":"Multiplicative Linear",
  "tags":["regen"],"base":80,
  "notes":"盾奶（Shield Mage）核心技能（build 必备 1-3 层）：原地站桩时回复翻倍，移动时归零；对站桩输出/坦价值极高。移动输入才触发归零，惯性滑行不算。"},
 {"id":"big_and_round","en":"Big and Round","jp":"大きな柱","zh":"巨大且圆润","rarity":"Rare",
  "desc":"Knockback Resistance +50% (+50% per stack); Max HP +30 (+30 per stack); Jump Height -10% (-10% per stack); Movement Speed -10% (-10% per stack)","descZh":"击退抗性 +50%（每层+50%）；最大生命 +30（每层+30）；跳跃高度 -10%（每层-10%）；移速 -10%（每层-10%）","stack":"Hyperbolic/Linear",
  "tags":["hp","knockback"],"base":55,
  "notes":"坦向堆叠；击退抗性过高会降低利用击退位移的能力，移速 -10% 对 Spellhammer 冲锋有影响。盾奶后期 HP 调节可选。"},
 {"id":"cold_blooded","en":"Cold Blooded","jp":"冷血","zh":"冷血","rarity":"Rare",
  "desc":"Reduce FREEZING stacks taken by X (X per stack); FROST Defense +15% (+15% per stack); FIRE Defense -15% (-15% per stack)","descZh":"减少冰冻层数；冰抗 +15%（每层+15%）；火抗 -15%（每层-15%）","stack":"Linear",
  "tags":["res_frost"],"base":35,
  "notes":"针对冰冻地图/冰 boss 的抗性装；火抗 -15% 是代价。按对局敌人类型选。"},
 {"id":"conductive_armor","en":"Conductive Armor","jp":"コンダクティブ・アーマー","zh":"导电护甲","rarity":"Rare",
  "desc":"PHYSICAL Defense +20% (+20% per stack); Reduce BLEEDING stacks by X (+X per stack); ELEMENTAL Defense -5% (-5% per stack)","descZh":"物理防御 +20%（每层+20%）；减少出血层数；元素防御 -5%（每层-5%）","stack":"Linear",
  "tags":["defense","res_bleed"],"base":60,
  "notes":"物理伤害为主的环境收益极高；盾奶 build 推荐 1-2 层。元素防御 -5% 代价较小。"},
 {"id":"holy_blessing","en":"Holy Blessing","jp":"聖なる祝福","zh":"圣光祝福","rarity":"Rare",
  "desc":"Falling to LOW HP causes a large explosion dealing 275 (+X per stack) LUMINOUS damage with 100% WEAKENED chance. LUMINOUS Defense +15%; SHADOW Defense +15%; Overall Damage -10% per stack","descZh":"进入低血量时引发大爆炸，造成 275（每层+X）圣光伤害并 100% 施加虚弱；圣/暗抗 +15%；总伤害 -10%（每层）","stack":"Linear",
  "tags":["defense","dmg"],"base":45,
  "notes":"低血量保底反制技能；总伤害 -10% 是代价，输出职业慎选。盾奶可选 1 层（build 推荐）。"},
 {"id":"iron_skin","en":"Iron Skin","jp":"アイアンスキン","zh":"铁皮","rarity":"Rare",
  "desc":"Defense +8% (+8% per stack); Movement Speed -3% (-3% per stack); Overall Damage -2% (-2% per stack)","descZh":"防御 +8%（每层+8%）；移速 -3%（每层-3%）；总伤害 -2%（每层-2%）","stack":"Linear",
  "tags":["defense"],"base":50,
  "notes":"盾奶 build 明确不建议（'いらない'）：移速与伤害代价高，防御收益一般。坦克可选少量。"},
 {"id":"last_stand","en":"Last Stand","jp":"最後の抵抗","zh":"背水一战","rarity":"Rare",
  "desc":"Upon taking damage which leaves you at 1 HP, receive X stacks of INVINCIBLE","descZh":"受到伤害降至 1 HP 时获得 X 层无敌","stack":"Linear",
  "tags":["survival"],"base":75,
  "notes":"保命神技，与 Volatile Tenacity（不安定な執念）相性极佳（日文 wiki 明确推荐搭配）。盾奶/坦必带 1 层。"},
 {"id":"life_leech","en":"Life Leech","jp":"ライフリーチ","zh":"生命汲取","rarity":"Rare",
  "desc":"Restore 1 (+1 per stack) HP upon dealing damage. Overall Damage -10% (-10% per stack); Health Regeneration -50% (-50% per stack); Received Healing -20% (-20% per stack)","descZh":"造成伤害回 1 HP（每层+1）；总伤害 -10%（每层）；自然回复 -50%（每层）；受疗 -20%（每层）","stack":"Linear",
  "tags":["lifesteal"],"base":30,
  "notes":"代价极大：伤害、自然回复、受疗全降。仅高频攻击自保流可选，普通局不推荐。"},
 {"id":"masochist","en":"Masochist","jp":"マゾヒスト","zh":"受虐狂","rarity":"Rare",
  "desc":"Reduce PARALYZED stacks taken by X (X per stack); ELECTRIC Defense +15% (+15% per stack); PHYSICAL Defense -10% (-15% per stack)","descZh":"减少麻痹层数；电抗 +15%（每层+15%）；物理防御 -10%（每层-15%）","stack":"Linear",
  "tags":["res_electric"],"base":30,
  "notes":"针对电属性环境（如雷 boss）；物理抗性代价明显。"},
 {"id":"natures_gift","en":"Nature's Gift","jp":"ヒーリングオーラ","zh":"自然馈赠","rarity":"Rare",
  "desc":"Spawn up to 3 (+1 per level) personal Healing Auras at random locations every 10 seconds, healing 20 HP each","descZh":"每 10 秒在随机位置生成最多 3（每层+1）个治疗光环，每个回 20 HP","stack":"Linear",
  "tags":["regen"],"base":25,
  "notes":"位置随机，实战价值有限；站桩坦偶尔能吃到。"},
 {"id":"benison_purification","en":"Benison of Purification","jp":"清めの祝福","zh":"净化祝福","rarity":"Legendary",
  "desc":"Periodically fire a projectile dealing 25 (+X per stack) LUMINOUS damage at closest enemy within 64m. SHADOW Defense +10%; Overall Defense -5% per stack","descZh":"周期性向 64 米内最近敌人发射 25（每层+X）圣光弹；暗抗 +10%；总防御 -5%（每层）","stack":"Linear",
  "tags":["dmg","defense"],"base":60,
  "notes":"免费白嫖输出 + 暗抗；盾奶 build 推荐 1 层。总防御 -5% 轻微代价。"},
 {"id":"big_and_wrathful","en":"Big and Wrathful","jp":"巨大な憤怒","zh":"巨大且暴怒","rarity":"Legendary",
  "desc":"Damage dealt at LOW HP +50%; Raise LOW HP threshold by 10%; Defense at LOW HP -25%","descZh":"低血量时伤害 +50%；低血量阈值 +10%；低血量防御 -25%","stack":"Linear/Hyperbolic",
  "tags":["dmg","lowhp"],"base":65,
  "notes":"狂暴流核心：配合 Nekomancer 的 Necropact（死之契约）等低血量机制极佳（日文 wiki 推荐）。坦克慎用。"},
 {"id":"curse_of_wrath","en":"Curse of Wrath","jp":"憤怒の呪い","zh":"愤怒诅咒","rarity":"Legendary",
  "desc":"Periodically fire a projectile dealing 25 (+X per stack) SHADOW damage at closest enemy within 32m. LUMINOUS Defense -20% (-20% per stack)","descZh":"周期性向 32 米内最近敌人发射 25（每层+X）暗影弹；圣光防御 -20%（每层）","stack":"Linear",
  "tags":["dmg"],"base":55,
  "notes":"免费输出；圣光防御 -20% 在圣光 boss 局（如 Jim 圣光攻击）代价高。"},
 {"id":"glass_cannon","en":"Glass Cannon","jp":"ガラスキャノン","zh":"玻璃大炮","rarity":"Legendary",
  "desc":"Damage +30% (+30% per stack); Health -50 (-50 per stack)","descZh":"伤害 +30%（每层+30%）；生命 -50（每层-50）","stack":"Linear",
  "tags":["dmg"],"base":70,
  "notes":"输出核心；每层 -50 HP 代价极大，一般 1-2 层。盾奶 build 用它调节过高的 HP（'HP 太高就用玻璃炮降'）。"},
 {"id":"healthy_guard","en":"Healthy Guard","jp":"ヘルシーガード","zh":"健康守护","rarity":"Legendary",
  "desc":"After being at FULL HP for 15 seconds (-X seconds per stack), next instance of damage reduced by 50% (+50% per stack)","descZh":"满血 15 秒（每层-X 秒）后，下一次受到的伤害降低 50%（每层+50%）","stack":"Linear/Hyperbolic",
  "tags":["survival"],"base":65,
  "notes":"对紫（贯穿）攻击也有效，且能降低复活队友的 50% HP 代价至 25%（日文 wiki 实测）。奶妈/坦克 1 层。"},
 {"id":"mass_aspect","en":"Mass Aspect","jp":"集積の様相","zh":"质量面相","rarity":"Legendary",
  "desc":"Health +75 (+75 per stack); Movement Speed -30% (-30% per stack)","descZh":"生命 +75（每层+75）；移速 -30%（每层-30%）","stack":"Linear",
  "tags":["hp"],"base":45,
  "notes":"高 HP 高代价；坦克 1 层即可，移速 -30% 对需要走位的职业伤害大。"},
 {"id":"volatile_tenacity","en":"Volatile Tenacity","jp":"不安定な執念","zh":"不稳定韧性","rarity":"Legendary",
  "desc":"Upon taking lethal damage when above LOW HP, survive with 1 HP. 150s cooldown (+25% cooldown rate per stack)","descZh":"高于低血量阈值时受到致命伤害不会死，保留 1 HP。冷却 150 秒（每层冷却速率+25%）","stack":"Linear",
  "tags":["survival"],"base":90,
  "notes":"最强保命技，日文 wiki 多职业 build 必带 1 层；与 Last Stand 组合可形成免死链。注意持续伤害/多段攻击仍会打死。"},
]
