# -*- coding: utf-8 -*-
# Ecliptica 数据 Part 3: Chrono Wizard (时空法师商店) 20 技能

SHOP_CHRONO = [
 {"id":"full_focus","en":"Full Focus","jp":"集中","zh":"全神贯注","rarity":"Common",
  "desc":"Critical Strike Chance +5% (+5% per stack); Critical Strike Damage +5% (+5% per stack)","descZh":"暴击率 +5%（每层+5%）；暴击伤害 +5%（每层+5%）","stack":"Linear",
  "tags":["crit"],"base":65,
  "notes":"暴击率软上限 40% 硬上限 60%；暴伤硬上限 385%。注意与 Pocket Abacus（爆算盘，暴击率归零）冲突：日文 wiki 实测取 2 层以上 Full Focus 时爆算盘反而降低伤害。"},
 {"id":"potent_strike","en":"Potent Strike","jp":"強烈な一撃","zh":"强力一击","rarity":"Common",
  "desc":"Critical strikes have 6% (+6% per stack) higher chance to inflict a status effect","descZh":"暴击施加状态异常概率 +6%（每层+6%）","stack":"Linear",
  "tags":["crit","status"],"base":45,
  "notes":"异常流（Twinmage/光法暴击异常）辅助技能。"},
 {"id":"sorcerers_mastery","en":"Sorcerer's Mastery","jp":"魔導師達の極意","zh":"法师的奥义","rarity":"Common",
  "desc":"ELEMENTAL Damage +8% (+8% per stack)","descZh":"元素伤害 +8%（每层+8%）","stack":"Linear",
  "tags":["elem_dmg"],"base":65,
  "notes":"法系核心堆叠；物理职业（Fistmage/Spellhammer 主物理）价值低。"},
 {"id":"strength","en":"Strength","jp":"ストレングス","zh":"力量","rarity":"Common",
  "desc":"PHYSICAL Damage +10% (+10% per stack)","descZh":"物理伤害 +10%（每层+10%）","stack":"Linear",
  "tags":["phys_dmg"],"base":60,
  "notes":"物理职业核心；法系价值低。"},
 {"id":"iq_too_high","en":"An IQ Too High?","jp":"IQが高すぎる？","zh":"智商太高了？","rarity":"Rare",
  "desc":"ELEMENTAL Damage +25% (+25% per stack); Projectile Speed -15% (-15% per stack); Attack Speed -10% (-10% per stack)","descZh":"元素伤害 +25%（每层+25%）；弹速 -15%（每层-15%）；攻速 -10%（每层-10%）","stack":"Linear",
  "tags":["elem_dmg"],"base":70,
  "notes":"法系强力增伤；弹速惩罚用 Eagle Eye 抵消（Thaumaturge build 建议配 4+ Eagle Eye）。取 2 层后用 Swift Hands 补攻速（日文 build）。"},
 {"id":"clutch_or_kick","en":"Clutch or Kick","jp":"背水の陣","zh":"绝境反扑","rarity":"Rare",
  "desc":"Gain +7% (+7% per stack) Overall Damage for every dead player in the party","descZh":"每名阵亡队友提供 +7%（每层+7%）总伤害","stack":"Linear",
  "tags":["dmg"],"base":30,
  "notes":"单排不出现；正常团战队友很少死，价值低。'背水の陣'。"},
 {"id":"cutting_edge","en":"Cutting Edge","jp":"鋭利な刃","zh":"锋刃","rarity":"Rare",
  "desc":"Chance to inflict BLEEDING +10% (+10% per stack); PHYSICAL Defense -5% (-5% per stack)","descZh":"施加出血概率 +10%（每层+10%）；物理防御 -5%（每层-5%）","stack":"Linear",
  "tags":["status"],"base":50,
  "notes":"出血流核心（Spellsword 极意配合：出血回血）；物理输出职业收益高。"},
 {"id":"fire_aspect","en":"Fire Aspect","jp":"火の様相","zh":"火焰面相","rarity":"Rare",
  "desc":"FIRE Defense +15%; FIRE Damage +15%; BURNING chance +5%; FROST Defense -10% per stack","descZh":"火抗 +15%（每层）；火伤 +15%（每层）；灼烧概率 +5%（每层）；冰抗 -10%（每层）","stack":"Linear",
  "tags":["elem_dmg","res_fire"],"base":55,
  "notes":"火系职业（Twinmage 火焰手/火法）核心；火抗提升附带生存收益。"},
 {"id":"frost_aspect","en":"Frost Aspect","jp":"氷の様相","zh":"寒冰面相","rarity":"Rare",
  "desc":"FROST Defense +15%; FROST Damage +15%; FROZEN chance +5%; FIRE Defense -10% per stack","descZh":"冰抗 +15%（每层）；冰伤 +15%（每层）；冰冻概率 +5%（每层）；火抗 -10%（每层）","stack":"Linear",
  "tags":["elem_dmg","res_frost"],"base":55,
  "notes":"冰系职业核心（Twinmage 冰手）。"},
 {"id":"greater_focus","en":"Greater Focus","jp":"死中に活","zh":"绝境专注","rarity":"Rare",
  "desc":"Critical Strike Chance at low HP +10% (+10% per stack); Critical Strike Damage +3% (+3% per stack)","descZh":"低血量时暴击率 +10%（每层+10%）；暴伤 +3%（每层+3%）","stack":"Linear",
  "tags":["crit","lowhp"],"base":45,
  "notes":"低血量暴击流（配合 Big and Wrathful/低血量机制）。"},
 {"id":"luminous_aspect","en":"Luminous Aspect","jp":"聖の様相","zh":"圣光面相","rarity":"Rare",
  "desc":"LUMINOUS Damage +15%; SHADOW Defense +15%; WEAKENED chance +5%; ELEMENTAL Defense -5% per stack","descZh":"圣光伤害 +15%（每层）；暗抗 +15%（每层）；虚弱概率 +5%（每层）；元素防御 -5%（每层）","stack":"Linear",
  "tags":["elem_dmg"],"base":60,
  "notes":"光法（Divine Hand）核心——B站实测光法伤害数值 50 远超其他元素 30，'光法是真的顶'，当前版本最强输出流。"},
 {"id":"poison_aspect","en":"Poison Aspect","jp":"毒の様相","zh":"剧毒面相","rarity":"Rare",
  "desc":"POISON Damage +15%; POISON Defense +15%; POISONED chance +5%; Received Healing -5% per stack","descZh":"毒伤 +15%（每层）；毒抗 +15%（每层）；中毒概率 +5%（每层）；受疗 -5%（每层）","stack":"Linear",
  "tags":["elem_dmg"],"base":50,
  "notes":"毒奶（书奶 Thaumaturge）辅助；v0.51 受疗 -15%→-5% 缓和，但社区仍不建议书奶抓取（'依旧不太建议抓取'）。"},
 {"id":"shadow_aspect","en":"Shadow Aspect","jp":"闇の様相","zh":"暗影面相","rarity":"Rare",
  "desc":"SHADOW Damage +15%; BREACHED chance +5%; LUMINOUS Defense -10% per stack","descZh":"暗影伤害 +15%（每层）；破甲概率 +5%（每层）；圣光防御 -10%（每层）","stack":"Linear",
  "tags":["elem_dmg"],"base":55,
  "notes":"暗属性枪手/暗法核心；圣光防御代价在圣光 boss 局注意。"},
 {"id":"sticky","en":"Sticky","jp":"粘着性","zh":"粘性","rarity":"Rare",
  "desc":"Apply 2 (+2 per stack) additional stacks of status effects against enemies. Negative status effects apply X (+X per stack) additional stacks to you","descZh":"对敌人施加的状态异常额外 +2（每层+2）层；自身受到的负面状态也增加","stack":"Linear",
  "tags":["status"],"base":45,
  "notes":"异常流双刃剑：自身负面层数也增加，需搭配抗性/净化。"},
 {"id":"charged_strike","en":"Charged Strike","jp":"チャージドストライク","zh":"充能打击","rarity":"Legendary",
  "desc":"Critical Hits cause an explosion dealing X (+X per stack) PHYSICAL damage; Critical Strike Chance -5% (-5% per stack)","descZh":"暴击引发 X（每层+X）物理伤害爆炸；暴击率 -5%（每层-5%）","stack":"Linear",
  "tags":["crit","dmg"],"base":55,
  "notes":"暴击爆炸；暴击率惩罚注意。伤害属性为物理（B站评论区提问确认场景）。"},
 {"id":"flaming_spirit","en":"Flaming Spirit","jp":"炎の守護霊","zh":"烈焰之灵","rarity":"Legendary",
  "desc":"When at full HP, primary skill fires a fireball dealing 16 (+X per stack) FIRE damage. Received Healing -5%; Health Regeneration -20% per stack","descZh":"满血时使用主手技能发射火球造成 16（每层+X）火伤；受疗 -5%（每层）；自然回复 -20%（每层）","stack":"Linear",
  "tags":["dmg"],"base":60,
  "notes":"**与 Frozen Heart 互斥**（日文 wiki：'どちらかしか取得できない'）。Thaumaturge build 认为满血火球是'回复资源获取最强'技能（必带 1 层）。"},
 {"id":"frozen_heart","en":"Frozen Heart","jp":"凍てついた心","zh":"寒冰之心","rarity":"Legendary",
  "desc":"When at full HP, primary skill fires an icicle dealing 18 (+X per stack) FROST damage. Received Healing -5%; Health Regeneration -20% per stack","descZh":"满血时使用主手技能发射冰锥造成 18（每层+X）冰伤；受疗 -5%（每层）；自然回复 -20%（每层）","stack":"Linear",
  "tags":["dmg"],"base":55,
  "notes":"**与 Flaming Spirit 互斥**。日文 build 明确'凍てついた心は劣化（降级版）'，冰系可选。"},
 {"id":"pocket_abacus","en":"Pocket Abacus","jp":"携帯そろばん","zh":"便携算盘","rarity":"Legendary",
  "desc":"Every fifth instance of damage becomes a guaranteed Critical Strike. Critical Strike Damage +10%; Non-Critical Damage -10%; Sets Critical Strike Chance to 0%","descZh":"每第 5 次伤害必暴击；暴伤 +10%（每层）；非暴击伤害 -10%（每层）；暴击率归零","stack":"Linear",
  "tags":["crit","dmg"],"base":60,
  "notes":"稳定暴击流核心；与 Full Focus 冲突（日文 wiki 有详细期望值计算：1 层时 vs 集中收益约 2.97% 提升，2 层集中后收益变差）。高频攻击职业最佳。"},
 {"id":"third_law","en":"Third Law","jp":"反作用","zh":"第三定律","rarity":"Legendary",
  "desc":"Upon taking damage, deal 150% (+25% per stack) of its RAW value to enemies around you as PHYSICAL damage. On Fistmage's Parry, deal 50% of the damage around you","descZh":"受到伤害时向周围敌人反弹 150%（每层+25%）原始值物理伤害；Fistmage 格挡时反弹 50%","stack":"Linear",
  "tags":["dmg"],"base":55,
  "notes":"v0.51 更新：Fistmage 格挡也触发（反弹固定 50%），并新增范围光环显示。坦克/反伤流核心。"},
 {"id":"warriors_will","en":"Warrior's Will","jp":"戦士の意志","zh":"战士意志","rarity":"Legendary",
  "desc":"Using your Utility Skill grants 4 (+2 per stack) stacks of EMPOWERED; Utility Cooldown Rate -15% (-15% per stack)","descZh":"使用辅助技能获得 4（每层+2）层强力；辅助 CD 速率 -15%（每层-15%）","stack":"Linear",
  "tags":["utility"],"base":55,
  "notes":"Spellsword 短 CD 位移（Quick Dash）可常驻强力（日文 wiki 推荐），Gunmancer/其他频繁 Utility 职业也可用。"},
]
