# -*- coding: utf-8 -*-
# Ecliptica 数据 Part 7: 各职业最终理想加点 Build（社区验证 + 机制分析）
# source: 日文wiki build页 / B站社区实战 / 机制推导（推断项标注）

BUILDS = [
 {"classId":"thaumaturge","patch":"v0.51 (2026-07-29)","title":"稳定型远程奶妈（书奶）","source":"日文wiki build页+社区实机验证",
  "must":[
   {"id":"th_keen_eye","count":7,"reason":"Jim Phase2/3 远程奶防事故的必需射程；妥协可 6"},
   {"id":"th_proficiency","count":7,"reason":"奶量+CD 双核心（v0.51 CD 缩短被削 15%→10%，更需要堆）"},
   {"id":"th_doping","count":1,"reason":"最强守护奶技，没抽到可考虑转生；v0.51 自我上限 3 层、CD+15%"},
   {"id":"flaming_spirit","count":1,"reason":"满血火球=回复资源获取最强（与寒冰之心互斥，冰版是降级）"},
   {"id":"eagle_eye","count":5,"reason":"弹速抵消 IQ 惩罚；4 层保底"},
   {"id":"athletic","count":None,"reason":"移速堆到 140 附近（含暗号记录/其他来源），别开局多拿"},
  ],
  "nice":[
   {"id":"th_mastery","count":None,"reason":"能量消耗 -3%/层，24% 硬上限=8 层封顶；见必拿"},
   {"id":"th_splashback","count":None,"reason":"无代价 75 毒伤爆炸；近战队伍更赚"},
   {"id":"volatile_tenacity","count":1,"reason":"保命；配最后抵抗"},
   {"id":"last_stand","count":1,"reason":"配不稳定韧性；怕死选它"},
   {"id":"healthy_guard","count":1,"reason":"满血减伤+复活成本降半"},
   {"id":"mass_aspect","count":None,"reason":"HP 不够 200 时用；铁皮不要，导电护甲全拿"},
   {"id":"iq_too_high","count":2,"reason":"元素 +25%/层；取 2 后补 1 迅捷之手"},
   {"id":"conductive_armor","count":None,"reason":"物理防御+出血抗性"},
  ],
  "avoid":[
   {"id":"th_splitshot","reason":"1 层都别取：近战化+扩散，生存崩盘"},
   {"id":"th_everlife","reason":"复活代价=50秒废人+永久-25HP；理念冲突"},
   {"id":"poison_aspect","reason":"v0.51 受疗惩罚缓解但仍不建议"},
  ],
  "playstyle":"鹰眼+锐眼让你边打边看全场；痛苦交换的时机与目标选择是核心，差插奶的瞄准+血量判断能力要求高。",
  "reroll":"先看蓝（忍耐）绿（机动）→ 最后看红（时空）。红只在有必须传奇/奥义时才取；红只出伤害系就 reroll。必须项拿完前手动 reroll 只给红。青绿看到必须/准必须直接拿；拿完青绿必要数量后，红公共系补到需要数量再 reroll。伤害系多且必须项拿完→留 token 下轮。后期 HP 不稳可用绿 reroll。",
 },
 {"classId":"shieldmage","patch":"v0.50 (2026-07-08)","title":"站桩坦克（相信队友）","source":"日文wiki build页",
  "must":[
   {"id":"big_and_lazy","count":3,"reason":"核心：站桩自然回复翻倍（1-3 层），没有它坦度天壤之别"},
   {"id":"vitality","count":10,"reason":"自然回复是坦主要恢复源（按大且懒的取得度调整）"},
   {"id":"sm_unbreakable","count":9,"reason":"紫攻击减免+钉住敌人；8-10 层"},
   {"id":"sm_proficiency","count":3,"reason":"盾范围扩大，杂鱼战接八方攻击更稳（2-3 层）"},
   {"id":"last_stand","count":1,"reason":"事故保险"},
   {"id":"volatile_tenacity","count":1,"reason":"同上"},
   {"id":"big_and_speedy","count":1,"reason":"辅助 CD 加快=仇恨节奏；注意防御 -20%"},
  ],
  "nice":[
   {"id":"fluffy","count":None,"reason":"HP 补到 150-250；太高仇恨不稳可用玻璃炮回调"},
   {"id":"big_and_round","count":None,"reason":"HP+击退抗性；击退抗性别堆满（会失去击退位移）"},
   {"id":"benison_purification","count":1,"reason":"免费输出+虚弱减伤"},
   {"id":"thunder_aura","count":2,"reason":"免费 AOE+麻痹控制"},
   {"id":"conductive_armor","count":2,"reason":"物理抗性+出血抗性"},
   {"id":"sm_ice_burst","count":1,"reason":"格挡转输出"},
  ],
  "avoid":[
   {"id":"sm_warden","reason":"辅助 CD +50% 代价太重（v0.51 缓和后仍重）"},
  ],
  "playstyle":"杂鱼战保护后排仇恨；门卫战拉仇恨到角落站桩，成为队友掩体；紫攻击必须开护罩/躲。站得住就赢。",
  "reroll":"大且懒+不坏是硬目标；Eclipse 难度前还没拿到大且懒→考虑转生重开。",
 },
 {"classId":"twinmage","patch":"v0.51 (2026-07-29)","title":"光法（圣光手 Divine Hand）速攻流","source":"B站社区实战（光法带飞/光法舒适区）+机制分析",
  "must":[
   {"id":"luminous_aspect","count":None,"reason":"圣光伤害+虚弱施加；当前版本光伤数值最高（50 vs 其他 30）"},
   {"id":"swift_hands","count":None,"reason":"攻速拉到 200% 即可（B站实测），再往上收益递减"},
   {"id":"tm_mastery","count":2,"reason":"技能触发 25% 爆炸增伤；2 层后收益薄"},
   {"id":"rapid_fire","count":None,"reason":"攻速 +50%/层；200% 前核心，注意总伤 -20%"},
   {"id":"sorcerers_mastery","count":None,"reason":"元素伤害核心堆叠"},
  ],
  "nice":[
   {"id":"iq_too_high","count":2,"reason":"元素 +25%；配鹰眼补弹速"},
   {"id":"eagle_eye","count":None,"reason":"弹速抵消 IQ 惩罚"},
   {"id":"potent_strike","count":None,"reason":"暴击异常流辅助"},
   {"id":"full_focus","count":None,"reason":"暴击率/暴伤；注意与爆算盘冲突（2 层以上集中反而亏）"},
   {"id":"pocket_abacus","count":1,"reason":"稳定必暴；高频攻击职业收益高（光法攻速快叠层快）"},
   {"id":"berserker_soul_ranged","count":1,"reason":"无伤流核心：满层 +45% 伤/+90% 攻速"},
   {"id":"tm_dextra","count":None,"reason":"右手=圣光手则强化右手"},
   {"id":"cutting_edge","count":None,"reason":"出血+暴击异常"},
   {"id":"thunder_aura","count":None,"reason":"受击雷霆玩法；总伤 -10% 代价"},
  ],
  "avoid":[
   {"id":"tm_sinistra","reason":"主右手光手时左手强化无用"},
   {"id":"way_of_the_law","reason":"输出节奏随机"},
   {"id":"life_leech","reason":"代价过大"},
  ],
  "playstyle":"远程站桩输出；Jim 对策可带右手物法（近战 4 连拳？）+ 异常 buff；白蓝异常 buff 都可拿，金道中可拿。",
  "reroll":"优先红（时空）找光面相/爆算盘/狂战魂；蓝绿补攻速弹速。",
 },
 {"classId":"spellhammer","patch":"v0.51 (2026-07-29)","title":"核爆锤（投掷 Chuck 流）","source":"B站社区实战（核爆锤/落槌点位）+机制分析",
  "must":[
   {"id":"sh_prof_chuck","count":None,"reason":"v0.51 附加爆炸伤害=锤本体+爆炸 2 段；核心"},
   {"id":"sh_juggernaut_chuck","count":1,"reason":"满蓄力投掷→强力 buff；核爆核心（上限 5 层+2/升级）"},
   {"id":"sh_mastery_chuck","count":None,"reason":"弹跳+1 次；核爆玩法组件"},
   {"id":"heavy_hand","count":None,"reason":"单发高伤职业适配（投掷不吃攻速流）"},
   {"id":"glass_cannon","count":1,"reason":"+30% 伤害；1 层即可"},
  ],
  "nice":[
   {"id":"springfoot","count":None,"reason":"跳高→跳砸伤害缩放；跳砸流必拿"},
   {"id":"sh_prof_jump","count":None,"reason":"跳砸流基础"},
   {"id":"sh_mastery_jump","count":None,"reason":"踩头减 CD 连段"},
   {"id":"sh_juggernaut_jump","count":None,"reason":"跳砸流生存"},
   {"id":"strength","count":None,"reason":"物理伤害核心"},
   {"id":"athletic","count":None,"reason":"移速→挥击冲锋距离"},
   {"id":"partial_flight","count":None,"reason":"二段跳优化跳砸连段"},
   {"id":"smell_the_roses","count":None,"reason":"低血量保命"},
  ],
  "avoid":[
   {"id":"rapid_fire","reason":"攻速流与投掷蓄力流冲突"},
   {"id":"swift_hands","reason":"同上（蓄力投掷不吃攻速）"},
   {"id":"way_of_the_law","reason":"节奏随机"},
  ],
  "playstyle":"蓄力投掷为主，满蓄力（准星变红）出手；核爆锤玩法：起爆符符文互叠，白嫖至少 6 个力量；本局下砸伤害上限约 1550。",
  "reroll":"红找重手/玻璃炮/投掷系；蓝绿补物理伤害与移速跳高。",
 },
 {"classId":"nekomancer","patch":"v0.51 (2026-07-29)","title":"猫奶推进流","source":"B站社区（猫奶通关/书奶猫奶分工）+机制分析",
  "must":[
   {"id":"nk_proficiency","count":None,"reason":"掉魂率核心，猫是本体"},
   {"id":"nk_death_blossom","count":None,"reason":"图腾猫治疗强化；-3% 总伤代价小"},
   {"id":"vitality","count":None,"reason":"自然回复支撑"},
   {"id":"fluffy","count":None,"reason":"HP 补强（猫术士初始 HP 低）"},
  ],
  "nice":[
   {"id":"nk_mastery","count":None,"reason":"每魂 +2% 伤害；与死亡契约冲突"},
   {"id":"nk_soul_detonation","count":None,"reason":"猫死爆炸；需操作"},
   {"id":"nk_necropact","count":None,"reason":"低血量猫扛伤；配巨大且暴怒极佳"},
   {"id":"big_and_wrathful","count":None,"reason":"低血量增伤流（配死亡契约）"},
   {"id":"benison_purification","count":None,"reason":"免费输出"},
   {"id":"eagle_eye","count":None,"reason":"弹速（法杖）"},
  ],
  "avoid":[
   {"id":"smell_the_roses","reason":"低血量脱离机制与死亡契约冲突"},
  ],
  "playstyle":"推怪流：猫奶适合清小怪（吸收死怪能量），书奶适合打 BOSS；后期召唤物 HP 不足需注意保护图腾猫。",
  "reroll":"蓝绿找生存+魂系；红找死亡契约/暴怒。",
 },
 {"classId":"fistmage","patch":"v0.51 (2026-07-29)","title":"格挡反伤流","source":"B站社区（拳击手单挑Jim/受击雷霆）+机制分析",
  "must":[
   {"id":"fm_proficiency","count":None,"reason":"格挡回血+团队光环"},
   {"id":"fm_rage","count":None,"reason":"格挡→4 秒攻速翻倍；核心爆发"},
   {"id":"fm_mastery","count":None,"reason":"格挡→强力+守护"},
   {"id":"fm_apply_force","count":None,"reason":"格挡→远程投射物；核心输出"},
   {"id":"third_law","count":None,"reason":"v0.51 格挡也触发反弹（50%）；反伤流核心"},
   {"id":"conductive_armor","count":None,"reason":"物理抗性+出血抗性"},
  ],
  "nice":[
   {"id":"fm_mach_punch","count":None,"reason":"移速增伤"},
   {"id":"athletic","count":None,"reason":"移速（马赫拳联动）"},
   {"id":"strength","count":None,"reason":"物理伤害"},
   {"id":"thunder_aura","count":None,"reason":"受击雷霆玩法：挨打叠狂乱+电伤"},
   {"id":"reactive_panic","count":None,"reason":"受伤叠狂乱"},
   {"id":"volatile_tenacity","count":None,"reason":"保命"},
  ],
  "avoid":[
   {"id":"fm_runner","reason":"v0.51 削弱，价值下降"},
  ],
  "playstyle":"格挡是生命线：挡成功=回血+buff+反伤+攻速；没挡住=站桩挨打。Jim 战靠格挡节奏硬吃。",
  "reroll":"红找第三定律/力量；蓝绿找攻速移速。",
 },
 {"classId":"gunmancer","patch":"v0.51 (2026-07-29)","title":"蓄力重炮流","source":"B站社区（电光枪速通/光枪输出）+机制分析",
  "must":[
   {"id":"gm_mastery","count":None,"reason":"蓄力射击 +50% 伤害；核心"},
   {"id":"gm_prof_photon","count":None,"reason":"v0.51 加强（+1→+2 弹）；光子凝聚器流核心"},
   {"id":"swift_hands","count":None,"reason":"攻速（蓄力时间也吃攻速）"},
   {"id":"eagle_eye","count":None,"reason":"弹速（VA-11 是 hit-scan 不吃；弹道副手吃）"},
  ],
  "nice":[
   {"id":"gm_sidestep","count":2,"reason":"2 层常驻急速"},
   {"id":"gm_overcharged","count":None,"reason":"电枪流"},
   {"id":"gm_prof_antimatter","count":None,"reason":"暗枪流（配暗影面相）"},
   {"id":"shadow_aspect","count":None,"reason":"暗枪流核心"},
   {"id":"gm_prof_firebomb","count":None,"reason":"喷子流（毒奶喷子玩法）"},
   {"id":"berserker_soul_ranged","count":None,"reason":"无伤流核心"},
   {"id":"warriors_will","count":None,"reason":"辅助技能叠强力"},
   {"id":"gm_marksman","count":None,"reason":"硬币机制娱乐/高伤"},
  ],
  "avoid":[
   {"id":"springfoot","reason":"跳跃流对枪手收益低"},
  ],
  "playstyle":"蓄力射击（位移后空中'シャキン'再主/副手）=核心输出；v0.51 光枪偏弱，物理枪一般，光法更强——枪手需靠熟练度弥补。",
  "reroll":"红找枪术士奥义/狂战魂；蓝绿补攻速弹速。",
 },
 {"classId":"spellsword","patch":"v0.51 (2026-07-29)","title":"旋风出血流","source":"B站社区（全员牢剑通关）+日文wiki机制分析",
  "must":[
   {"id":"ss_whirlwind","count":None,"reason":"远程化核心：旋风穿透持续伤害；v0.51 出血回血翻倍使其更强"},
   {"id":"ss_mastery","count":3,"reason":"出血回血（v0.51 1→2）；代价自然回复 -100%"},
   {"id":"cutting_edge","count":None,"reason":"出血概率核心"},
   {"id":"ss_swift_stab","count":None,"reason":"移速增伤无副作用"},
  ],
  "nice":[
   {"id":"ss_proficiency","count":None,"reason":"射程+狂乱叠层（v0.51）"},
   {"id":"ss_burst","count":None,"reason":"位移后攻速爆发"},
   {"id":"athletic","count":None,"reason":"移速→突刺增伤联动"},
   {"id":"warriors_will","count":None,"reason":"位移叠强力"},
   {"id":"strength","count":None,"reason":"物理伤害"},
   {"id":"ss_shieldbreaker","count":None,"reason":"v0.51 念力斩 +25%；格挡敌人特化"},
  ],
  "avoid":[
   {"id":"pocket_abacus","reason":"旋风暴击判定无效，暴击流不适用"},
   {"id":"full_focus","reason":"同上"},
  ],
  "playstyle":"旋风是本体：蓄满力→发射→穿透刮痧大型敌人+挂出血回血；前期近战，后期远程化。'牢剑'评价=操作要求高但成型强。",
  "reroll":"红找旋风/迅捷突刺/力量；蓝绿补移速攻速。",
 },
]
